import { DEFAULT_MONO_FONT_STACK, DEFAULT_UI_FONT_STACK } from "../theme";
import { radii, shadow, stack, type DesignVariantDefinition } from "./definition";

export const focusVariant: DesignVariantDefinition = {
  id: "focus",
  label: "Focus",
  tagline: "Minimal and airy. A centred reading column, borderless panels, the composer up front.",
  references: ["Cursor", "Devin", "Perplexity Computer"],
  light: {
    surface0: "#ffffff",
    surface1: "#fcfcfc",
    surface2: "#f5f5f5",
    surface3: "#ebebeb",
    surface4: "#dcdcdc",
    surfaceDiffEmpty: "#f7f7f7",
    surfaceSidebar: "#f9f9f9",
    foreground: "#171717",
    foregroundMuted: "#737373",
    foregroundExtraMuted: "#a3a3a3",
    border: "#efefef",
    borderAccent: "#f3f3f3",
    accent: "#2563eb",
    accentBright: "#3b82f6",
    accentForeground: "#ffffff",
    primary: "#171717",
    primaryForeground: "#ffffff",
    destructive: "#c0392b",
    terminalBlack: "#171717",
    terminalBrightBlack: "#404040",
    ring: "#93b4f5",
  },
  dark: {
    surface0: "#1a1a1a",
    surface1: "#1f1f1f",
    surface2: "#262626",
    surface3: "#333333",
    surface4: "#454545",
    surfaceDiffEmpty: "#202020",
    surfaceSidebar: "#151515",
    foreground: "#e8e8e8",
    foregroundMuted: "#9b9b9b",
    foregroundExtraMuted: "#666666",
    border: "#282828",
    borderAccent: "#2e2e2e",
    accent: "#4c8dff",
    accentBright: "#86b0ff",
    accentForeground: "#ffffff",
    destructive: "#d9534f",
    terminalBlack: "#151515",
    terminalBrightBlack: "#454545",
    ring: "#4c8dff",
  },
  borderRadius: radii(4, 6, 8, 10, 12, 16),
  lightShadow: shadow("0, 0, 0", [0.03, 0.05, 0.08]),
  darkShadow: shadow("0, 0, 0", [0.3, 0.35, 0.5]),
  design: {
    frame: "flat",
    composer: "floating",
    userMessage: "card",
    density: "comfortable",
    borderless: true,
    monoMeta: false,
    contentMaxWidth: 720,
    controlRadius: 8,
    uiFontFamily: stack(`Inter, ${DEFAULT_UI_FONT_STACK}`, DEFAULT_UI_FONT_STACK),
    monoFontFamily: stack(`'JetBrains Mono', ${DEFAULT_MONO_FONT_STACK}`, DEFAULT_MONO_FONT_STACK),
    headingFontFamily: stack(`Inter, ${DEFAULT_UI_FONT_STACK}`, DEFAULT_UI_FONT_STACK),
    contentFontFamily: null,
    headingLetterSpacing: -0.4,
    headingWeight: "600",
  },
  webFonts: ["Inter:wght@400;500;600;700", "JetBrains+Mono:wght@400;500"],
};
