import { DEFAULT_MONO_FONT_STACK, DEFAULT_UI_FONT_STACK } from "../theme";
import { radii, shadow, stack, type DesignVariantDefinition } from "./definition";

export const insetVariant: DesignVariantDefinition = {
  id: "inset",
  label: "Inset",
  tagline: "Dense, keyboard-first. Content floats as an inset card on a quiet frame.",
  references: ["Linear", "Plain"],
  light: {
    surface0: "#ffffff",
    surface1: "#fbfbfc",
    surface2: "#f4f4f6",
    surface3: "#e8e8ec",
    surface4: "#d6d6dc",
    surfaceDiffEmpty: "#f6f6f8",
    surfaceSidebar: "#f2f2f4",
    foreground: "#1b1c1f",
    foregroundMuted: "#6b6f76",
    foregroundExtraMuted: "#a0a3aa",
    border: "#e6e6ea",
    borderAccent: "#ededf0",
    accent: "#5e6ad2",
    accentBright: "#7480e0",
    accentForeground: "#ffffff",
    primary: "#1b1c1f",
    primaryForeground: "#ffffff",
    destructive: "#c2413a",
    terminalBlack: "#1b1c1f",
    terminalBrightBlack: "#3f3f46",
    ring: "#5e6ad2",
  },
  dark: {
    surface0: "#131417",
    surface1: "#18191d",
    surface2: "#1e1f24",
    surface3: "#2b2d34",
    surface4: "#3b3d46",
    surfaceDiffEmpty: "#1a1b20",
    surfaceSidebar: "#0c0d0f",
    foreground: "#eeeff1",
    foregroundMuted: "#9a9ca5",
    foregroundExtraMuted: "#62646c",
    border: "#23252b",
    borderAccent: "#2c2e35",
    accent: "#5e6ad2",
    accentBright: "#8b93ea",
    accentForeground: "#ffffff",
    destructive: "#d05a5a",
    terminalBlack: "#0c0d0f",
    terminalBrightBlack: "#3b3d46",
    ring: "#8b93ea",
  },
  borderRadius: radii(3, 4, 5, 6, 8, 10),
  lightShadow: shadow("16, 18, 35", [0.04, 0.06, 0.1]),
  darkShadow: shadow("0, 0, 0", [0.3, 0.35, 0.5]),
  design: {
    frame: "inset",
    composer: "box",
    userMessage: "bubble",
    density: "compact",
    borderless: false,
    monoMeta: false,
    contentMaxWidth: null,
    controlRadius: 6,
    uiFontFamily: stack(`Inter, ${DEFAULT_UI_FONT_STACK}`, DEFAULT_UI_FONT_STACK),
    monoFontFamily: DEFAULT_MONO_FONT_STACK,
    headingFontFamily: stack(`Inter, ${DEFAULT_UI_FONT_STACK}`, DEFAULT_UI_FONT_STACK),
    contentFontFamily: null,
    headingLetterSpacing: -0.2,
    headingWeight: "600",
  },
  webFonts: ["Inter:wght@400;500;600;700"],
};
