import { DEFAULT_MONO_FONT_STACK, DEFAULT_UI_FONT_STACK } from "../theme";
import { radii, shadow, stack, type DesignVariantDefinition } from "./definition";

export const monoVariant: DesignVariantDefinition = {
  id: "mono",
  label: "Mono",
  tagline: "High-contrast black and white, hairlines, mono metadata. Built for status at a glance.",
  references: ["Vercel", "v0"],
  light: {
    surface0: "#ffffff",
    surface1: "#fafafa",
    surface2: "#f2f2f2",
    surface3: "#e8e8e8",
    surface4: "#d4d4d4",
    surfaceDiffEmpty: "#f7f7f7",
    surfaceSidebar: "#fafafa",
    foreground: "#0a0a0a",
    foregroundMuted: "#666666",
    foregroundExtraMuted: "#a3a3a3",
    border: "#ebebeb",
    borderAccent: "#f0f0f0",
    accent: "#0a0a0a",
    accentBright: "#333333",
    accentForeground: "#ffffff",
    primary: "#0a0a0a",
    primaryForeground: "#ffffff",
    destructive: "#d93036",
    terminalBlack: "#0a0a0a",
    terminalBrightBlack: "#3a3a3a",
    ring: "#0a0a0a",
  },
  dark: {
    surface0: "#000000",
    surface1: "#0a0a0a",
    surface2: "#121212",
    surface3: "#1f1f1f",
    surface4: "#2e2e2e",
    surfaceDiffEmpty: "#0d0d0d",
    surfaceSidebar: "#000000",
    foreground: "#ededed",
    foregroundMuted: "#a1a1a1",
    foregroundExtraMuted: "#6e6e6e",
    border: "#242424",
    borderAccent: "#2e2e2e",
    accent: "#ededed",
    accentBright: "#ffffff",
    accentForeground: "#000000",
    destructive: "#e5484d",
    terminalBlack: "#0a0a0a",
    terminalBrightBlack: "#3a3a3a",
    ring: "#ededed",
  },
  borderRadius: radii(4, 5, 6, 6, 8, 12),
  lightShadow: shadow("0, 0, 0", [0.04, 0.06, 0.1]),
  darkShadow: shadow("0, 0, 0", [0.5, 0.6, 0.7]),
  design: {
    frame: "flat",
    composer: "box",
    userMessage: "plain",
    density: "regular",
    borderless: false,
    monoMeta: true,
    contentMaxWidth: null,
    controlRadius: 6,
    uiFontFamily: stack(`Geist, Inter, ${DEFAULT_UI_FONT_STACK}`, DEFAULT_UI_FONT_STACK),
    monoFontFamily: stack(`'Geist Mono', ${DEFAULT_MONO_FONT_STACK}`, DEFAULT_MONO_FONT_STACK),
    headingFontFamily: stack(`Geist, Inter, ${DEFAULT_UI_FONT_STACK}`, DEFAULT_UI_FONT_STACK),
    contentFontFamily: null,
    headingLetterSpacing: -0.5,
    headingWeight: "600",
  },
  webFonts: ["Geist:wght@400;500;600;700", "Geist+Mono:wght@400;500"],
};
