import { DEFAULT_MONO_FONT_STACK, DEFAULT_UI_FONT_STACK } from "../theme";
import { radii, shadow, SERIF_STACK, type DesignVariantDefinition } from "./definition";

export const paperVariant: DesignVariantDefinition = {
  id: "paper",
  label: "Paper",
  tagline: "Warm, editorial and calm. Serif headings and prose, soft ivory surfaces.",
  references: ["Claude", "Microsoft Copilot"],
  light: {
    surface0: "#faf9f5",
    surface1: "#f5f4ee",
    surface2: "#efede5",
    surface3: "#e5e2d6",
    surface4: "#d5d1c2",
    surfaceDiffEmpty: "#f3f1ea",
    surfaceSidebar: "#f0eee6",
    foreground: "#29261b",
    foregroundMuted: "#6b6557",
    foregroundExtraMuted: "#9c9686",
    border: "#e3dfd2",
    borderAccent: "#ebe8dd",
    accent: "#c96442",
    accentBright: "#d97757",
    accentForeground: "#ffffff",
    primary: "#29261b",
    primaryForeground: "#faf9f5",
    destructive: "#b5402f",
    terminalBlack: "#29261b",
    terminalBrightBlack: "#4a4745",
    ring: "#c96442",
  },
  dark: {
    surface0: "#262624",
    surface1: "#2b2a27",
    surface2: "#31302d",
    surface3: "#44433e",
    surface4: "#5a5853",
    surfaceDiffEmpty: "#2d2c29",
    surfaceSidebar: "#1f1e1d",
    foreground: "#f3f1ea",
    foregroundMuted: "#b7b2a6",
    foregroundExtraMuted: "#7f7a70",
    border: "#3a3935",
    borderAccent: "#44423d",
    accent: "#d97757",
    accentBright: "#e89a7f",
    accentForeground: "#ffffff",
    destructive: "#d0563f",
    terminalBlack: "#1f1e1d",
    terminalBrightBlack: "#4a4745",
    ring: "#e89a7f",
  },
  borderRadius: radii(4, 6, 8, 10, 14, 18),
  lightShadow: shadow("60, 45, 20", [0.04, 0.07, 0.1]),
  darkShadow: shadow("0, 0, 0", [0.25, 0.3, 0.45]),
  design: {
    frame: "flat",
    composer: "floating",
    userMessage: "bubble",
    density: "comfortable",
    borderless: true,
    monoMeta: false,
    contentMaxWidth: 760,
    controlRadius: 10,
    uiFontFamily: DEFAULT_UI_FONT_STACK,
    monoFontFamily: DEFAULT_MONO_FONT_STACK,
    headingFontFamily: SERIF_STACK,
    contentFontFamily: SERIF_STACK,
    headingLetterSpacing: -0.3,
    headingWeight: "500",
  },
  webFonts: ["Source+Serif+4:opsz,wght@8..60,400;8..60,500;8..60,600"],
};
