import { DEFAULT_MONO_FONT_STACK, DEFAULT_UI_FONT_STACK } from "../theme";
import { radii, shadow, stack, type DesignVariantDefinition } from "./definition";

export const softVariant: DesignVariantDefinition = {
  id: "soft",
  label: "Soft",
  tagline:
    "Friendly and tactile. Floating rounded panels, pill controls, soft depth. Mobile-first.",
  references: ["Perplexity", "ChatGPT iOS", "Notion iOS", "Arcade"],
  light: {
    surface0: "#fbfbf9",
    surface1: "#f6f6f3",
    surface2: "#efefeb",
    surface3: "#e3e4df",
    surface4: "#d2d3cd",
    surfaceDiffEmpty: "#f3f3ef",
    surfaceSidebar: "#eeefea",
    foreground: "#13343b",
    foregroundMuted: "#5f7377",
    foregroundExtraMuted: "#97a5a8",
    border: "#e3e5e0",
    borderAccent: "#eaece7",
    accent: "#20808d",
    accentBright: "#2ba0ae",
    accentForeground: "#ffffff",
    primary: "#13343b",
    primaryForeground: "#ffffff",
    destructive: "#c2453b",
    terminalBlack: "#13343b",
    terminalBrightBlack: "#3d5a60",
    ring: "#20808d",
  },
  dark: {
    surface0: "#1b1d1d",
    surface1: "#202323",
    surface2: "#272a2a",
    surface3: "#363a3a",
    surface4: "#484d4d",
    surfaceDiffEmpty: "#222525",
    surfaceSidebar: "#121414",
    foreground: "#e8eeee",
    foregroundMuted: "#9fb0b0",
    foregroundExtraMuted: "#6c7a7a",
    border: "#2b2f2f",
    borderAccent: "#333737",
    accent: "#3aaebd",
    accentBright: "#7fd3dd",
    accentForeground: "#062227",
    destructive: "#d86a5f",
    terminalBlack: "#121414",
    terminalBrightBlack: "#484d4d",
    ring: "#7fd3dd",
  },
  borderRadius: radii(6, 10, 12, 14, 18, 24),
  lightShadow: shadow("19, 52, 59", [0.05, 0.08, 0.12], 1.5),
  darkShadow: shadow("0, 0, 0", [0.3, 0.4, 0.55], 1.5),
  design: {
    frame: "floating",
    composer: "pill",
    userMessage: "bubble",
    density: "comfortable",
    borderless: true,
    monoMeta: false,
    contentMaxWidth: 780,
    controlRadius: 999,
    uiFontFamily: stack(`'Plus Jakarta Sans', ${DEFAULT_UI_FONT_STACK}`, DEFAULT_UI_FONT_STACK),
    monoFontFamily: DEFAULT_MONO_FONT_STACK,
    headingFontFamily: stack(
      `'Plus Jakarta Sans', ${DEFAULT_UI_FONT_STACK}`,
      DEFAULT_UI_FONT_STACK,
    ),
    contentFontFamily: null,
    headingLetterSpacing: -0.3,
    headingWeight: "700",
  },
  webFonts: ["Plus+Jakarta+Sans:wght@400;500;600;700"],
};
