import { brandEnv } from "../../../packages/branding/src/identity.js";
import {
  daemonArtifactName,
  legacyDaemonArtifactName,
  desktopArtifactName,
  legacyDesktopSuffix,
  desktopArtifactSuffixes,
  legacyArtifactCutoff,
} from "../../../packages/branding/src/artifacts.js";
import { mkdir, readFile, writeFile as writeRaw } from "node:fs/promises";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { root, outputRoot, uiOutput, type BrandBuild } from "./resolve.mjs";

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll('"', "&quot;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll("'", "&#39;");
}
/** `<PREFIX>_RELEASE_VERSION` (or `FROGG_RELEASE_VERSION`) set by the release build. */
function resolveReleaseVersion(brand: BrandBuild["brand"]): string | null {
  const value =
    brandEnv(brand, process.env, "RELEASE_VERSION") ?? process.env.FROGG_RELEASE_VERSION;
  const trimmed = value?.trim();
  return trimmed ? trimmed : null;
}

export async function generateConfig(build: BrandBuild): Promise<void> {
  const { brand, version, fingerprint } = build;
  const json = (value: unknown) => JSON.stringify(value, null, 2) + "\n";
  const generated = path.join(root, "packages/branding/src/generated");
  await mkdir(generated, { recursive: true });
  await writeFile(
    path.join(generated, "brand.ts"),
    `// Generated by brand:prepare.\nimport type { Brand } from "../schema.js";\nexport const resolvedBrand: Brand = ${json(brand).trim()};\n`,
  );
  // A downstream rebuild of an upstream version (`1.4.1-acme.2`) has no place to
  // put that number: the workspace version stays upstream's so merges do not
  // conflict on twenty manifests. Stamp it at build time instead, so the app can
  // report the build a user actually installed rather than the version it forked.
  await writeFile(
    path.join(generated, "release.ts"),
    `// Generated by brand:prepare.\nexport const releaseVersion: string | null = ${json(resolveReleaseVersion(brand)).trim()};\n`,
  );
  await writeFile(path.join(outputRoot, "brand.json"), json(brand));
  const manifest = JSON.parse(
    await readFile(path.join(root, "apps/ui/public/manifest.json"), "utf8"),
  );
  Object.assign(manifest, {
    id: brand.legacyFrogg ? "/" : `/${brand.id}`,
    name: brand.name,
    short_name: brand.name,
    description: brand.description,
    theme_color: brand.colors.dark.accent,
    background_color: brand.colors.dark.background,
  });
  await writeFile(path.join(uiOutput, "public/manifest.json"), json(manifest));
  let html = await readFile(path.join(root, "apps/ui/public/index.html"), "utf8");
  html = html
    .replace('content="Frogg"', `content="${escapeHtml(brand.name)}"`)
    .replaceAll("#25B5C8", brand.colors.dark.accent)
    .replaceAll("#25b5c8", brand.colors.dark.accent)
    .replaceAll("#181b1a", brand.colors.dark.background);
  await writeFile(path.join(uiOutput, "public/index.html"), html);
  const eas = JSON.parse(await readFile(path.join(root, "apps/ui/eas.json"), "utf8"));
  if (brand.distribution.iosStoreId)
    eas.submit.production.ios = { ascAppId: brand.distribution.iosStoreId };
  else delete eas.submit.production.ios;
  await writeFile(path.join(outputRoot, "eas.json"), json(eas));
  let revision = process.env.FROGG_SOURCE_REVISION ?? "unknown";
  if (revision === "unknown") {
    try {
      revision = execFileSync("git", ["rev-parse", "HEAD"], {
        cwd: root,
        encoding: "utf8",
        stdio: ["ignore", "pipe", "ignore"],
      }).trim();
    } catch {
      /* Exported source builds provide FROGG_SOURCE_REVISION. */
    }
  }
  await writeFile(
    path.join(outputRoot, "provenance.json"),
    json({
      schemaVersion: 1,
      brand: { id: brand.id, applicationId: brand.applicationId },
      version,
      sourceRevision: revision,
      configFingerprint: fingerprint,
    }),
  );
  const constants: Record<string, string | number | boolean> = {
    ID: brand.id,
    VERSION: version,
    CONFIG_FINGERPRINT: fingerprint,
    SOURCE_REVISION: revision,
    NAME: brand.name,
    FULL_NAME: brand.fullName,
    APPLICATION_ID: brand.applicationId,
    CLI_NAME: brand.cliName,
    DESKTOP_BINARY: brand.desktopBinaryName,
    HOME_DIR: brand.homeDir,
    ENV_PREFIX: brand.envPrefix,
    SCHEME: brand.scheme,
    SERVICE_NAME: brand.serviceName,
    LAUNCHD_LABEL: brand.launchdLabel,
    ARTIFACT_PREFIX: brand.artifactPrefix,
    DAEMON_ARTIFACT_PREFIX: brand.daemonArtifactPrefix,
    LEGACY_ARTIFACT_CUTOFF: legacyArtifactCutoff,
    DAEMON_ARTIFACT_NAMES: JSON.stringify(
      Object.fromEntries(
        ["linux", "darwin", "win"].flatMap((platform) =>
          ["x64", "arm64"].map((arch) => [
            `${platform}-${arch}`,
            {
              current: daemonArtifactName(brand, "{version}", platform, arch),
              legacy: legacyDaemonArtifactName(brand, "{version}", platform, arch),
            },
          ]),
        ),
      ),
    ),
    DESKTOP_ARTIFACT_NAMES: JSON.stringify(
      Object.fromEntries(
        desktopArtifactSuffixes.map((suffix) => [
          suffix,
          {
            current: desktopArtifactName(brand, "{version}", suffix),
            legacy: `${brand.artifactPrefix}-{version}-${legacyDesktopSuffix(suffix)}`,
          },
        ]),
      ),
    ),
    // The hostname pairing links use, so the Rust daemon's Host allowlist can
    // apply the same default allowance the Node daemon does.
    PAIRING_HOSTNAME: brand.services.pairingUrl
      ? new URL(brand.services.pairingUrl).hostname
      : "",
    WORKSPACE_SERVICES_BIND_HOST: brand.daemon.workspaceServicesBindHost,
    DEFAULT_PORT: brand.daemonPort,
    DEFAULT_LISTEN: `127.0.0.1:${brand.daemonPort}`,
    LEGACY_FROGG: brand.legacyFrogg,
    RELEASES_API: brand.distribution.releasesApi ?? "",
    RELEASE_BASE: brand.distribution.releaseBase ?? "",
    UPDATE_MODE: brand.distribution.updateMode,
  };
  const rust = Object.entries(constants)
    .map(([name, value]) => `pub const ${name}: ${rustType(value)} = ${JSON.stringify(value)};`)
    .join("\n");
  await writeFile(path.join(outputRoot, "brand.rs"), `// Generated by brand:prepare.\n${rust}\n`);
}

function rustType(value: string | number | boolean): string {
  if (typeof value === "number") return "u16";
  if (typeof value === "boolean") return "bool";
  return "&str";
}

export async function writeFile(file: string, contents: string): Promise<void> {
  try {
    if ((await readFile(file, "utf8")) === contents) return;
  } catch {
    /* New output. */
  }
  await writeRaw(file, contents);
}
