/* Round-4 fake data, layered on round-1 core.js (sessions, projects, agents). */
window.D = (function () {
  const hosts = [
    {
      id: "devbox",
      name: "devbox",
      kind: "Relay",
      status: "done",
      ver: "0.9.14",
      lat: "18 ms",
      os: "Ubuntu 24.04 · x64",
      cpu: 38,
      mem: 61,
      disk: 72,
      up: "12d 4h",
      sessions: 9,
    },
    {
      id: "macbook",
      name: "macbook",
      kind: "Local",
      status: "done",
      ver: "0.9.14",
      lat: "1 ms",
      os: "macOS 16 · arm64",
      cpu: 12,
      mem: 48,
      disk: 41,
      up: "3d 1h",
      sessions: 2,
      me: true,
    },
    {
      id: "ci-runner-2",
      name: "ci-runner-2",
      kind: "Remote SSH",
      status: "error",
      ver: "0.9.11",
      lat: "—",
      os: "Debian 13 · x64",
      cpu: 0,
      mem: 0,
      disk: 88,
      up: "—",
      sessions: 2,
      err: "SSH tunnel failed · connection refused on :22",
    },
  ];
  const tree = [
    [0, "dir", ".github", 0],
    [0, "dir", "apps", 0],
    [0, "dir", "packages", 1],
    [1, "dir", "protocol", 0],
    [1, "dir", "server", 1],
    [2, "dir", "src", 1],
    [3, "file", "db.ts", ""],
    [3, "file", "drafts.ts", ""],
    [3, "file", "session-store.ts", "M"],
    [3, "dir", "util", 1],
    [4, "file", "lru.ts", "A"],
    [3, "file", "write-queue.ts", "A"],
    [2, "dir", "test", 1],
    [3, "file", "session-store.test.ts", "M"],
    [2, "file", "package.json", ""],
    [1, "dir", "ui", 0],
    [0, "file", "frogg.json", ""],
    [0, "file", "package.json", ""],
    [0, "file", "README.md", ""],
  ];
  const code = [
    'import { LRU } from "./util/lru";',
    'import { WriteQueue } from "./write-queue";',
    'import type { Db, Session } from "./db";',
    "",
    "/** Persistent session store with a bounded cache and coalesced writes. */",
    "export function createSessionStore(db: Db) {",
    "  const cache = new LRU<string, Session>({ max: 500 });",
    "  const writes = new WriteQueue(db, { flushMs: 50 });",
    "",
    "  return {",
    "    get: async (id: string) => cache.get(id) ?? (await db.get(id)),",
    "    save: (s: Session) => {",
    "      cache.set(s.id, s);",
    "      writes.enqueue(s);",
    "    },",
    "    flush: () => writes.drain(),",
    "    size: () => cache.size,",
    "  };",
    "}",
  ];
  const commits = [
    ["a41f9c2", "Route session saves through WriteQueue", "Claude Code", "4m"],
    ["7be01d4", "Add LRU with size cap and eviction hook", "Claude Code", "11m"],
    ["e93c5aa", "Test: store survives 10k draft saves", "Claude Code", "16m"],
    ["1c0d7f3", "Merge main into feat/session-store", "you", "1h"],
  ];
  const prs = [
    {
      n: 1284,
      t: "Session store persistence refactor",
      br: "feat/session-store",
      st: "Draft",
      ses: "s1",
      checks: [3, 1, 1],
      rev: "0 of 1",
      mine: true,
    },
    {
      n: 1279,
      t: "Fix composer draft loss on reconnect",
      br: "fix/draft-loss",
      st: "Open",
      ses: "s2",
      checks: [5, 0, 0],
      rev: "1 of 1",
      mine: true,
    },
    {
      n: 1281,
      t: "Translate settings strings (9 locales)",
      br: "chore/i18n-settings",
      st: "Open",
      ses: "s5",
      checks: [4, 0, 1],
      rev: "0 of 1",
      mine: true,
    },
    {
      n: 1266,
      t: "Plugin API: panel refresh hooks",
      br: "feat/panel-refresh",
      st: "Merged",
      checks: [5, 0, 0],
      rev: "1 of 1",
    },
    {
      n: 1270,
      t: "Android: adaptive icon",
      br: "fix/adaptive-icon",
      st: "Closed",
      checks: [2, 1, 0],
      rev: "—",
    },
  ];
  const checks = [
    ["typecheck", "done", "42s"],
    ["lint", "done", "18s"],
    ["test (linux)", "done", "3m 12s"],
    ["test (windows)", "error", "4m 01s"],
    ["desktop build", "running", "4m…"],
  ];
  const runs = [
    {
      id: 8812,
      wf: "CI",
      br: "feat/session-store",
      ev: "push",
      st: "running",
      t: "4m",
      by: "Claude Code",
    },
    {
      id: 8809,
      wf: "CI",
      br: "fix/draft-loss",
      ev: "pull_request",
      st: "done",
      t: "11m",
      by: "Codex",
    },
    { id: 8807, wf: "Release · beta", br: "main", ev: "push", st: "done", t: "38m", by: "you" },
    {
      id: 8801,
      wf: "CI",
      br: "chore/i18n-settings",
      ev: "pull_request",
      st: "error",
      t: "52m",
      by: "Copilot",
    },
    {
      id: 8799,
      wf: "Nightly e2e",
      br: "main",
      ev: "schedule",
      st: "done",
      t: "6h",
      by: "schedule",
    },
    {
      id: "J-412",
      wf: "jenkins · android-release",
      br: "main",
      ev: "trigger",
      st: "idle",
      t: "queued",
      by: "jenkins",
    },
  ];
  const terms = [
    { id: "t1", name: "zsh", cwd: "~/frogg-app (feat/session-store)", st: "running", on: true },
    { id: "t2", name: "pnpm dev", cwd: "service · :5173", st: "running", svc: true },
    { id: "t3", name: "vitest --watch", cwd: "packages/server", st: "idle" },
  ];
  const scripts = [
    ["dev", "pnpm dev", "service", "running", "session-store.frogg.local", ":5173"],
    ["storybook", "pnpm storybook", "service", "idle", "", ":6006"],
    ["test", "pnpm test", "script", "done", "", "exit 0 · 3.1s"],
    ["typecheck", "pnpm typecheck", "script", "error", "", "exit 2 · 14s"],
  ];
  const plan = [
    ["Read session store, callers and tests", "done"],
    ["Bound the cache with an LRU (max 500)", "done"],
    ["Coalesce writes through a queue", "done"],
    ["Run server tests", "running"],
    ["Push and open a draft PR", "idle"],
    ["Write migration note for CHANGELOG", "idle"],
  ];
  const subagents = [
    ["Explore: callers of createSessionStore", "done", "12 files", "Explore"],
    ["Benchmark: draft-save write amplification", "running", "run 3/5", "general"],
    ["Review: concurrency in WriteQueue", "permission", "wants to run node bench.js", "reviewer"],
  ];
  const todos = [
    ["T-41", "Bound session store memory", "In progress", "High", "Claude Code · s1", "daemon"],
    ["T-44", "Retry Stripe webhooks with jitter", "Blocked", "Urgent", "Codex · s6", "billing"],
    ["T-38", "Push approvals on Android", "Claimed", "High", "Claude Code · s4", "mobile"],
    ["T-47", "Settings strings in 9 locales", "Review", "Medium", "Copilot · s5", "i18n"],
    ["T-49", "Notification inbox (persisted)", "Ready", "High", "", "ui"],
    ["T-50", "Unify permission mode labels", "Ready", "Medium", "", "ui"],
    ["T-51", "Single daemon update path", "Backlog", "Medium", "", "daemon"],
    ["T-52", "Expose vim mode toggle", "Backlog", "Low", "", "ui"],
    ["T-36", "Runner disk cleanup cron", "Done", "Low", "OpenCode · s11", "infra"],
  ];
  const providers = [
    {
      id: "claude",
      name: "Claude Code",
      st: "Available",
      models: 6,
      ver: "2.4.1",
      latest: "2.4.1",
      on: true,
      acct: 2,
    },
    {
      id: "codex",
      name: "Codex",
      st: "Available",
      models: 5,
      ver: "0.71.0",
      latest: "0.73.0",
      on: true,
      acct: 1,
    },
    {
      id: "copilot",
      name: "Copilot",
      st: "Available",
      models: 9,
      ver: "1.0.12",
      latest: "1.0.12",
      on: true,
      acct: 1,
    },
    {
      id: "opencode",
      name: "OpenCode",
      st: "Error",
      models: 0,
      ver: "0.18.3",
      latest: "0.19.0",
      on: true,
      acct: 0,
      err: "opencode serve exited (code 127): bun not found on PATH",
    },
    {
      id: "pi",
      name: "Oh My Pi",
      st: "Available",
      models: 4,
      ver: "3.2.0",
      latest: "3.2.0",
      on: true,
      acct: 1,
    },
    {
      id: "cursor",
      name: "Cursor",
      st: "Not installed",
      models: 0,
      ver: "—",
      latest: "1.6.0",
      on: false,
      acct: 0,
    },
    {
      id: "kimi",
      name: "Kimi",
      st: "Disabled",
      models: 3,
      ver: "0.4.0",
      latest: "0.4.0",
      on: false,
      acct: 0,
    },
  ];
  const accounts = [
    {
      id: "work",
      prov: "Claude Code",
      name: "steve@work",
      plan: "Max 20×",
      def: true,
      color: "#25b5c8",
      w: [
        ["5h", 42, "resets 1h 12m"],
        ["Week", 86, "resets Thu 09:00"],
        ["Opus week", 71, "resets Thu 09:00"],
      ],
    },
    {
      id: "personal",
      prov: "Claude Code",
      name: "personal",
      plan: "Pro",
      color: "#8b7cf6",
      w: [
        ["5h", 8, "resets 4h 40m"],
        ["Week", 31, "resets Sun 18:00"],
      ],
    },
    {
      id: "openai",
      prov: "Codex",
      name: "steve@openai",
      plan: "Pro",
      color: "#3fcf8e",
      w: [
        ["5h", 63, "resets 2h 05m"],
        ["Week", 54, "resets Mon 00:00"],
      ],
    },
    {
      id: "gh",
      prov: "Copilot",
      name: "stevehughes",
      plan: "Business",
      color: "#f5b84a",
      w: [["Premium requests", 23, "214 of 900 · resets Nov 1"]],
    },
    {
      id: "pi",
      prov: "Oh My Pi",
      name: "pi-api",
      plan: "API · $",
      color: "#ff6b6b",
      w: [["Balance", 37, "$18.40 of $50.00"]],
    },
  ];
  const devices = [
    ["Steve’s MacBook Pro", "Owner", "This device · connected", "macbook"],
    ["Pixel 9", "Operator", "Connected · viewing “Invoice PDF renderer”", "phone"],
    ["Firefox · ubuntu-ws", "Operator", "Last seen 2h ago", "web"],
    ["iPad (Ana)", "Viewer", "Last seen 3d ago", "tablet"],
  ];
  const plugins = [
    {
      id: "sentry",
      name: "Sentry",
      tier: "Official",
      st: "Active",
      ver: "1.4.0",
      on: true,
      where: "Host",
      desc: "Issues for the session’s release, attach stack traces to chat.",
      panel: "Sentry issues",
      hue: ["#8b7cf6", "#362d59"],
    },
    {
      id: "linear",
      name: "Linear",
      tier: "User",
      st: "Active",
      ver: "0.9.2",
      on: true,
      where: "Host",
      desc: "Link sessions to issues, sync status on PR merge.",
      panel: "Linear",
      hue: ["#7fd9e6", "#5e6ad2"],
    },
    {
      id: "docker",
      name: "Docker",
      tier: "Brand",
      st: "Active",
      ver: "2.1.0",
      upd: "2.2.0",
      on: true,
      where: "Host",
      desc: "Containers and compose services per session.",
      hue: ["#25b5c8", "#045b9d"],
    },
    {
      id: "bundle",
      name: "bundle-size",
      tier: "Local",
      st: "Error",
      ver: "dev",
      on: true,
      where: "Host",
      desc: "Local plugin: compare bundle size to main.",
      err: "manifest: views[0].entry not found",
      hue: ["#f5b84a", "#e0605a"],
    },
    {
      id: "pomo",
      name: "Focus timer",
      tier: "User",
      st: "Disabled",
      ver: "1.0.1",
      on: false,
      where: "This client",
      desc: "Pomodoro timer in the status bar.",
      hue: ["#3fcf8e", "#045b9d"],
    },
  ];
  const catalog = [
    ["GitLab", "Official", "Source control", "MRs, pipelines and approvals for GitLab forges."],
    ["Vercel", "Official", "Deploy", "Preview deployments per session branch."],
    ["Postgres", "Brand", "Data", "Read-only schema browser and query panel."],
    ["Grafana", "User", "Observability", "Pin dashboards beside a session."],
    ["Playwright", "Official", "Testing", "Trace viewer and flaky test panel."],
    ["Slack", "User", "Notify", "Forward inbox items to a channel."],
  ];
  const notes = [
    {
      k: "permission",
      t: "Fix composer draft loss on reconnect",
      d: "Codex wants to run pnpm db:migrate --env staging",
      ago: "1m",
      ses: "s2",
      unread: true,
    },
    {
      k: "permission",
      t: "Invoice PDF renderer",
      d: "Plan ready for review · 6 steps",
      ago: "2m",
      ses: "s7",
      unread: true,
    },
    {
      k: "error",
      t: "Stripe webhook retries",
      d: "exit 1 · retry.test.ts › backs off on 429",
      ago: "4m",
      ses: "s6",
      unread: true,
    },
    {
      k: "done",
      t: "Translate settings strings (9 locales)",
      d: "Finished · +912 −40 · ready to review",
      ago: "6m",
      ses: "s5",
      unread: true,
    },
    {
      k: "error",
      t: "Terraform drift check",
      d: "ci-runner-2 unreachable · SSH tunnel failed",
      ago: "12m",
      ses: "s12",
    },
    {
      k: "ci",
      t: "CI failed on chore/i18n-settings",
      d: "test (windows) · 2 failed, 118 passed",
      ago: "52m",
      ses: "s5",
    },
    {
      k: "done",
      t: "Runner disk cleanup cron",
      d: "Finished · PR #1277 merged, session archived",
      ago: "40m",
      ses: "s11",
    },
    {
      k: "system",
      t: "Storage growing on devbox",
      d: "Worktrees use 21.4 GiB (warning at 20 GiB)",
      ago: "1h",
    },
    {
      k: "plugin",
      t: "Sentry",
      d: "New issue in 0.9.14-beta.3: TypeError in reconnect()",
      ago: "2h",
    },
    { k: "system", t: "Codex 0.73.0 available", d: "Installed 0.71.0 on devbox", ago: "3h" },
    {
      k: "device",
      t: "Pairing request on devbox",
      d: "Firefox · ubuntu-ws wants Operator access · code 4F-K2",
      ago: "5h",
    },
  ];
  const models = [
    [
      "Claude Code",
      [
        ["Opus 5.5", "Default · 1M ctx", true],
        ["Sonnet 5", "Fast · 1M ctx"],
        ["Haiku 5", "Cheapest"],
      ],
    ],
    [
      "Codex",
      [
        ["GPT-5.3 Codex", "Default"],
        ["GPT-5.3 Codex Mini", ""],
      ],
    ],
    [
      "Copilot",
      [
        ["Gemini 3 Pro", ""],
        ["GPT-5.3", ""],
      ],
    ],
  ];
  // Unified permission vocabulary (provider-native names as subtitles).
  const modes = [
    [
      "Plan",
      "Read and propose; nothing changes until you approve the plan",
      { "Claude Code": "Plan Mode", Codex: "Plan feature", Copilot: "Plan", OpenCode: "Plan" },
    ],
    [
      "Ask",
      "Ask before every edit and command",
      {
        "Claude Code": "Always Ask",
        Codex: "Default Permissions",
        Copilot: "Agent",
        OpenCode: "—",
      },
    ],
    [
      "Auto-edit",
      "Edit files freely, ask before commands",
      { "Claude Code": "Accept File Edits", Codex: "Auto-review", Copilot: "—", OpenCode: "Build" },
    ],
    [
      "Auto",
      "Provider decides what is safe; asks for risky actions",
      { "Claude Code": "Auto mode", Codex: "—", Copilot: "—", OpenCode: "—" },
    ],
    [
      "Unattended",
      "Never asks. Use in sandboxes and throwaway worktrees",
      { "Claude Code": "Bypass", Codex: "Full Access", Copilot: "Allow All", OpenCode: "—" },
    ],
  ];
  const labels = [
    ["daemon", "Sky", "#38bdf8", 4],
    ["ui", "Violet", "#8b7cf6", 6],
    ["urgent", "Red", "#ff6b6b", 2],
    ["mobile", "Emerald", "#3fcf8e", 3],
    ["infra", "Orange", "#fb923c", 2],
  ];
  return {
    hosts,
    tree,
    code,
    commits,
    prs,
    checks,
    runs,
    terms,
    scripts,
    plan,
    subagents,
    todos,
    providers,
    accounts,
    devices,
    plugins,
    catalog,
    notes,
    models,
    modes,
    labels,
  };
})();
