/** Plugins manager, plugin contributions and consent copy, one entry per locale. */
const en = {
  title: "Plugins",
  disabledByBrand: "Plugins are turned off for this build.",
  devBadge: "DEV",
  tabs: {
    installed: "Installed",
    browse: "Browse",
    repositories: "Repositories",
  },
  target: {
    label: "Install on",
    client: "This client",
    host: "Host",
    none: "No hosts support plugins",
  },
  client: {
    installedEmpty: "No plugins installed on this device.",
    loadFailed: "Could not read this device's plugins: {{error}}",
    unsupported: "Client plugins run in the desktop and web apps.",
    addFolder: "Add local folder",
    addFolderHint: "Link a plugin folder on this computer. Linked plugins skip integrity checks.",
    linked: "Linked {{name}}.",
    reload: "Reload",
    consentTitle: "Install {{name}} on this device",
    consentIntro: "{{name}} runs inside this app on this device. It asks to:",
    sandboxed:
      "It runs in a sandbox with no access to the app's windows, storage or other plugins.",
    browseEmpty: "No client plugins available.",
    starting: "Starting",
    hybridInstall: "Install on this device",
    hybridInstalled: "Client component installed on this device",
    hybridUnsupported: "Client component: needs the desktop or web app.",
    hybridDev: "Client component: link its folder from This client in the desktop app.",
    hybridFailed: "Client component failed: {{error}}",
    needsClient:
      "Part of this plugin runs in the app: install its client component on each device.",
  },
  status: {
    active: "Active",
    disabled: "Disabled",
    error: "Error",
    incompatible: "Incompatible",
    blocked: "Blocked",
    inactive: "Inactive",
  },
  tier: {
    official: "Official",
    brand: "Brand",
    user: "User",
    dev: "Local",
  },
  capabilities: {
    network: "Make network requests",
    filesystem_workspace: "Read and write files in workspaces",
    process_spawn: "Run programs on the host",
    agent_read: "Read agent sessions and their events",
    agent_write: "Send messages to agents",
    settings_store: "Store its own settings",
    ui_contribute: "Add commands, buttons and panels",
    rpc: "Answer requests from the app",
    ui_view: "Show its own views in the app",
    media_microphone: "Use the microphone",
    media_audio: "Play audio",
    composer: "Add composer buttons and insert text",
    speech: "Use the host's speech recognition and voices",
  },
  errors: {
    withDetail: "{{summary}} {{detail}}",
    not_found: "Not found.",
    invalid_request: "The request was invalid.",
    forbidden: "Not allowed.",
    consent_required: "This update needs new permissions.",
    signature_invalid: "The repository signature did not verify.",
    hash_mismatch: "The download did not match its checksum.",
    manifest_mismatch: "The plugin did not match its repository entry.",
    fetch_failed: "Could not download from the repository.",
    incompatible: "Not compatible with this host.",
    already_installed: "Already installed.",
    plugin_error: "The plugin reported an error.",
    not_active: "The plugin is not running.",
    timeout: "The request timed out.",
    internal: "Something went wrong on the host.",
  },
  installed: {
    empty: "No plugins installed on this host.",
    meta: "{{id}} · v{{version}}",
    enable: "Enable {{name}}",
    updateAvailable: "Update to v{{version}}",
    needsClientComponent:
      "Part of this plugin runs in the app: install its client component on each device.",
    update: "Update",
    settings: "Settings",
    unlink: "Unlink",
    uninstall: "Uninstall",
    uninstallTitle: "Uninstall {{name}}?",
    uninstallMessage: "{{name}} and its stored settings will be removed from this host.",
  },
  browse: {
    search: "Search plugins",
    clearSearch: "Clear search",
    retry: "Retry",
    repoFailed: "{{name}} could not be loaded: {{error}}",
    empty: "No plugins available from your repositories.",
    noMatches: "No plugins match your search.",
    uncategorised: "Other",
    installed: "Installed v{{version}}",
    install: "Install",
    needsClient: "Needs client component",
    incompatible: "No version is compatible with this host.",
  },
  consent: {
    installTitle: "Install {{name}}",
    updateTitle: "Update {{name}}",
    installIntro: "This plugin asks for the following permissions:",
    updateIntro: "This update asks for new permissions:",
    noCapabilities: "No special permissions.",
    notSandboxed:
      "Plugins run inside the host process and are not sandboxed. Only install plugins you trust.",
    userRepoWarning:
      "This plugin comes from a repository you added yourself, not an official or brand repository.",
    install: "Allow and install",
    update: "Allow and update",
  },
  repos: {
    addTitle: "Add repository",
    url: "Index URL",
    name: "Name (optional)",
    publicKey: "Public key (optional)",
    publicKeyHint:
      "Leave empty to trust the key the repository publishes the first time you add it.",
    add: "Add repository",
    remove: "Remove",
    count: "Plugins: {{count}}",
    key: "Key: {{key}}",
    pinnedTitle: "Added {{name}}",
    pinnedBody: "Pinned signing key: {{key}}. Check it matches the one the publisher shared.",
  },
  developer: {
    title: "Local plugins",
    forbidden: "Linking local plugins needs a beta build of the daemon.",
    hint: "Lets you link local plugin folders on {{host}}. Linked plugins skip signature checks and reload on change.",
    addFolder: "Add local folder",
    path: "Folder path",
    pathHint: "Absolute path to the plugin folder on {{host}}.",
    link: "Link folder",
    linked: "Linked {{name}}",
  },
  settings: {
    title: "{{name}} settings",
    none: "This plugin has no settings.",
    save: "Save",
    saved: "Settings saved",
  },
  fields: {
    choose: "Choose…",
    noOptions: "No options",
  },
  panel: {
    tooltip: "{{panel}} ({{plugin}})",
    invalidContent: "The plugin returned a panel this app cannot display.",
    retry: "Retry",
    empty: "Nothing to show.",
    submit: "Submit",
    submitted: "Submitted",
    viewUnsupported: "This view runs on desktop and web.",
    viewNeedsClient: "Install {{plugin}} on this device to open this view.",
    viewFailed: "Could not open this view: {{error}}",
  },
  sessionActions: {
    trigger: "Plugin actions",
  },
  composerActions: {
    trigger: "Plugin composer actions",
  },
  commandCenter: {
    section: "Plugins",
  },
};

type WidenStringLeaves<T> = {
  [K in keyof T]: T[K] extends string ? string : WidenStringLeaves<T[K]>;
};
export type PluginsCopy = WidenStringLeaves<typeof en>;

export const pluginsCopies: Record<
  "en" | "es" | "fr" | "ja" | "ko" | "pt-BR" | "ru" | "zh-CN" | "ar",
  PluginsCopy
> = {
  en,
  es: {
    title: "Plugins",
    disabledByBrand: "Los plugins están desactivados en esta compilación.",
    devBadge: "DEV",
    tabs: {
      installed: "Instalados",
      browse: "Explorar",
      repositories: "Repositorios",
    },
    target: {
      label: "Instalar en",
      client: "Este cliente",
      host: "Host",
      none: "Ningún host admite plugins",
    },
    client: {
      installedEmpty: "No hay plugins instalados en este dispositivo.",
      loadFailed: "No se pudieron leer los plugins de este dispositivo: {{error}}",
      unsupported: "Los plugins de cliente funcionan en las apps de escritorio y web.",
      addFolder: "Añadir carpeta local",
      addFolderHint:
        "Vincula una carpeta de plugin de este equipo. Los plugins vinculados omiten las comprobaciones de integridad.",
      linked: "{{name}} vinculado.",
      reload: "Recargar",
      consentTitle: "Instalar {{name}} en este dispositivo",
      consentIntro: "{{name}} se ejecuta dentro de esta app en este dispositivo. Solicita:",
      sandboxed:
        "Se ejecuta en un entorno aislado sin acceso a las ventanas, el almacenamiento ni otros plugins de la app.",
      browseEmpty: "No hay plugins de cliente disponibles.",
      starting: "Iniciando",
      hybridInstall: "Instalar en este dispositivo",
      hybridInstalled: "Componente de cliente instalado en este dispositivo",
      hybridUnsupported: "Componente de cliente: requiere la app de escritorio o web.",
      hybridDev:
        "Componente de cliente: vincula su carpeta desde Este cliente en la app de escritorio.",
      hybridFailed: "Falló el componente de cliente: {{error}}",
      needsClient:
        "Parte de este plugin se ejecuta en la app: instala su componente de cliente en cada dispositivo.",
    },
    status: {
      active: "Activo",
      disabled: "Desactivado",
      error: "Error",
      incompatible: "Incompatible",
      blocked: "Bloqueado",
      inactive: "Inactivo",
    },
    tier: {
      official: "Oficial",
      brand: "Marca",
      user: "Usuario",
      dev: "Local",
    },
    capabilities: {
      network: "Hacer solicitudes de red",
      filesystem_workspace: "Leer y escribir archivos en los espacios de trabajo",
      process_spawn: "Ejecutar programas en el host",
      agent_read: "Leer las sesiones de agentes y sus eventos",
      agent_write: "Enviar mensajes a los agentes",
      settings_store: "Guardar su propia configuración",
      ui_contribute: "Añadir comandos, botones y paneles",
      rpc: "Responder a solicitudes de la app",
      ui_view: "Mostrar sus propias vistas en la app",
      media_microphone: "Usar el micrófono",
      media_audio: "Reproducir audio",
      composer: "Añadir botones al editor e insertar texto",
      speech: "Usar el reconocimiento de voz y las voces del host",
    },
    errors: {
      withDetail: "{{summary}} {{detail}}",
      not_found: "No encontrado.",
      invalid_request: "La solicitud no era válida.",
      forbidden: "No permitido.",
      consent_required: "Esta actualización necesita nuevos permisos.",
      signature_invalid: "No se pudo verificar la firma del repositorio.",
      hash_mismatch: "La descarga no coincide con su suma de verificación.",
      manifest_mismatch: "El plugin no coincide con su entrada en el repositorio.",
      fetch_failed: "No se pudo descargar desde el repositorio.",
      incompatible: "No es compatible con este host.",
      already_installed: "Ya está instalado.",
      plugin_error: "El plugin informó de un error.",
      not_active: "El plugin no se está ejecutando.",
      timeout: "Se agotó el tiempo de espera de la solicitud.",
      internal: "Algo salió mal en el host.",
    },
    installed: {
      empty: "No hay plugins instalados en este host.",
      meta: "{{id}} · v{{version}}",
      enable: "Activar {{name}}",
      updateAvailable: "Actualizar a v{{version}}",
      needsClientComponent:
        "Parte de este plugin se ejecuta en la app: instala su componente de cliente en cada dispositivo.",
      update: "Actualizar",
      settings: "Configuración",
      unlink: "Desvincular",
      uninstall: "Desinstalar",
      uninstallTitle: "¿Desinstalar {{name}}?",
      uninstallMessage: "{{name}} y su configuración guardada se eliminarán de este host.",
    },
    browse: {
      search: "Buscar plugins",
      clearSearch: "Borrar búsqueda",
      retry: "Reintentar",
      repoFailed: "No se pudo cargar {{name}}: {{error}}",
      empty: "Tus repositorios no ofrecen plugins.",
      noMatches: "Ningún plugin coincide con la búsqueda.",
      uncategorised: "Otros",
      installed: "Instalado v{{version}}",
      install: "Instalar",
      needsClient: "Necesita componente de cliente",
      incompatible: "Ninguna versión es compatible con este host.",
    },
    consent: {
      installTitle: "Instalar {{name}}",
      updateTitle: "Actualizar {{name}}",
      installIntro: "Este plugin solicita los siguientes permisos:",
      updateIntro: "Esta actualización solicita nuevos permisos:",
      noCapabilities: "Sin permisos especiales.",
      notSandboxed:
        "Los plugins se ejecutan dentro del proceso del host y no están aislados. Instala solo plugins de confianza.",
      userRepoWarning:
        "Este plugin proviene de un repositorio que añadiste tú, no de un repositorio oficial o de la marca.",
      install: "Permitir e instalar",
      update: "Permitir y actualizar",
    },
    repos: {
      addTitle: "Añadir repositorio",
      url: "URL del índice",
      name: "Nombre (opcional)",
      publicKey: "Clave pública (opcional)",
      publicKeyHint:
        "Déjala vacía para confiar en la clave que publica el repositorio la primera vez que lo añades.",
      add: "Añadir repositorio",
      remove: "Quitar",
      count: "Plugins: {{count}}",
      key: "Clave: {{key}}",
      pinnedTitle: "{{name}} añadido",
      pinnedBody:
        "Clave de firma fijada: {{key}}. Comprueba que coincide con la que compartió el editor.",
    },
    developer: {
      title: "Plugins locales",
      forbidden: "Vincular plugins locales requiere una versión beta del daemon.",
      hint: "Permite vincular carpetas de plugins locales en {{host}}. Los plugins vinculados omiten la verificación de firma y se recargan al cambiar.",
      addFolder: "Añadir carpeta local",
      path: "Ruta de la carpeta",
      pathHint: "Ruta absoluta de la carpeta del plugin en {{host}}.",
      link: "Vincular carpeta",
      linked: "{{name}} vinculado",
    },
    settings: {
      title: "Configuración de {{name}}",
      none: "Este plugin no tiene configuración.",
      save: "Guardar",
      saved: "Configuración guardada",
    },
    fields: {
      choose: "Elegir…",
      noOptions: "Sin opciones",
    },
    panel: {
      tooltip: "{{panel}} ({{plugin}})",
      invalidContent: "El plugin devolvió un panel que esta app no puede mostrar.",
      retry: "Reintentar",
      empty: "No hay nada que mostrar.",
      submit: "Enviar",
      submitted: "Enviado",
      viewUnsupported: "Esta vista funciona en escritorio y web.",
      viewNeedsClient: "Instala {{plugin}} en este dispositivo para abrir esta vista.",
      viewFailed: "No se pudo abrir esta vista: {{error}}",
    },
    sessionActions: {
      trigger: "Acciones de plugins",
    },
    composerActions: {
      trigger: "Acciones de plugins del editor",
    },
    commandCenter: {
      section: "Plugins",
    },
  },
  fr: {
    title: "Plugins",
    disabledByBrand: "Les plugins sont désactivés dans cette version.",
    devBadge: "DEV",
    tabs: {
      installed: "Installés",
      browse: "Parcourir",
      repositories: "Dépôts",
    },
    target: {
      label: "Installer sur",
      client: "Ce client",
      host: "Hôte",
      none: "Aucun hôte ne prend en charge les plugins",
    },
    client: {
      installedEmpty: "Aucun plugin installé sur cet appareil.",
      loadFailed: "Impossible de lire les plugins de cet appareil : {{error}}",
      unsupported: "Les plugins client fonctionnent dans les apps de bureau et web.",
      addFolder: "Ajouter un dossier local",
      addFolderHint:
        "Liez un dossier de plugin de cet ordinateur. Les plugins liés ne sont pas vérifiés.",
      linked: "{{name}} lié.",
      reload: "Recharger",
      consentTitle: "Installer {{name}} sur cet appareil",
      consentIntro: "{{name}} s'exécute dans cette app sur cet appareil. Il demande à :",
      sandboxed:
        "Il s'exécute dans un bac à sable sans accès aux fenêtres, au stockage ni aux autres plugins de l'app.",
      browseEmpty: "Aucun plugin client disponible.",
      starting: "Démarrage",
      hybridInstall: "Installer sur cet appareil",
      hybridInstalled: "Composant client installé sur cet appareil",
      hybridUnsupported: "Composant client : nécessite l'app de bureau ou web.",
      hybridDev: "Composant client : liez son dossier depuis Ce client dans l'app de bureau.",
      hybridFailed: "Échec du composant client : {{error}}",
      needsClient:
        "Une partie de ce plugin s'exécute dans l'app : installez son composant client sur chaque appareil.",
    },
    status: {
      active: "Actif",
      disabled: "Désactivé",
      error: "Erreur",
      incompatible: "Incompatible",
      blocked: "Bloqué",
      inactive: "Inactif",
    },
    tier: {
      official: "Officiel",
      brand: "Marque",
      user: "Utilisateur",
      dev: "Local",
    },
    capabilities: {
      network: "Effectuer des requêtes réseau",
      filesystem_workspace: "Lire et écrire des fichiers dans les espaces de travail",
      process_spawn: "Lancer des programmes sur l’hôte",
      agent_read: "Lire les sessions d’agents et leurs événements",
      agent_write: "Envoyer des messages aux agents",
      settings_store: "Enregistrer ses propres réglages",
      ui_contribute: "Ajouter des commandes, boutons et panneaux",
      rpc: "Répondre aux requêtes de l’app",
      ui_view: "Afficher ses propres vues dans l'app",
      media_microphone: "Utiliser le micro",
      media_audio: "Lire de l'audio",
      composer: "Ajouter des boutons au compositeur et insérer du texte",
      speech: "Utiliser la reconnaissance vocale et les voix de l'hôte",
    },
    errors: {
      withDetail: "{{summary}} {{detail}}",
      not_found: "Introuvable.",
      invalid_request: "La requête n’était pas valide.",
      forbidden: "Non autorisé.",
      consent_required: "Cette mise à jour demande de nouvelles autorisations.",
      signature_invalid: "La signature du dépôt n’a pas pu être vérifiée.",
      hash_mismatch: "Le téléchargement ne correspond pas à sa somme de contrôle.",
      manifest_mismatch: "Le plugin ne correspond pas à son entrée dans le dépôt.",
      fetch_failed: "Impossible de télécharger depuis le dépôt.",
      incompatible: "Incompatible avec cet hôte.",
      already_installed: "Déjà installé.",
      plugin_error: "Le plugin a signalé une erreur.",
      not_active: "Le plugin n’est pas en cours d’exécution.",
      timeout: "La requête a expiré.",
      internal: "Un problème est survenu sur l’hôte.",
    },
    installed: {
      empty: "Aucun plugin installé sur cet hôte.",
      meta: "{{id}} · v{{version}}",
      enable: "Activer {{name}}",
      updateAvailable: "Mettre à jour vers v{{version}}",
      needsClientComponent:
        "Une partie de ce plugin s'exécute dans l'app : installez son composant client sur chaque appareil.",
      update: "Mettre à jour",
      settings: "Réglages",
      unlink: "Dissocier",
      uninstall: "Désinstaller",
      uninstallTitle: "Désinstaller {{name}} ?",
      uninstallMessage: "{{name}} et ses réglages enregistrés seront supprimés de cet hôte.",
    },
    browse: {
      search: "Rechercher des plugins",
      clearSearch: "Effacer la recherche",
      retry: "Réessayer",
      repoFailed: "Impossible de charger {{name}} : {{error}}",
      empty: "Aucun plugin disponible dans vos dépôts.",
      noMatches: "Aucun plugin ne correspond à la recherche.",
      uncategorised: "Autres",
      installed: "v{{version}} installée",
      install: "Installer",
      needsClient: "Composant client requis",
      incompatible: "Aucune version n’est compatible avec cet hôte.",
    },
    consent: {
      installTitle: "Installer {{name}}",
      updateTitle: "Mettre à jour {{name}}",
      installIntro: "Ce plugin demande les autorisations suivantes :",
      updateIntro: "Cette mise à jour demande de nouvelles autorisations :",
      noCapabilities: "Aucune autorisation particulière.",
      notSandboxed:
        "Les plugins s’exécutent dans le processus de l’hôte et ne sont pas isolés. N’installez que des plugins de confiance.",
      userRepoWarning:
        "Ce plugin provient d’un dépôt que vous avez ajouté vous-même, pas d’un dépôt officiel ou de la marque.",
      install: "Autoriser et installer",
      update: "Autoriser et mettre à jour",
    },
    repos: {
      addTitle: "Ajouter un dépôt",
      url: "URL de l’index",
      name: "Nom (facultatif)",
      publicKey: "Clé publique (facultative)",
      publicKeyHint:
        "Laissez vide pour faire confiance à la clé publiée par le dépôt lors du premier ajout.",
      add: "Ajouter le dépôt",
      remove: "Retirer",
      count: "Plugins : {{count}}",
      key: "Clé : {{key}}",
      pinnedTitle: "{{name}} ajouté",
      pinnedBody:
        "Clé de signature épinglée : {{key}}. Vérifiez qu’elle correspond à celle communiquée par l’éditeur.",
    },
    developer: {
      title: "Plugins locaux",
      forbidden: "Lier des plugins locaux nécessite une version bêta du daemon.",
      hint: "Permet de lier des dossiers de plugins locaux sur {{host}}. Les plugins liés ignorent la vérification de signature et se rechargent à chaque modification.",
      addFolder: "Ajouter un dossier local",
      path: "Chemin du dossier",
      pathHint: "Chemin absolu du dossier du plugin sur {{host}}.",
      link: "Lier le dossier",
      linked: "{{name}} lié",
    },
    settings: {
      title: "Réglages de {{name}}",
      none: "Ce plugin n’a pas de réglages.",
      save: "Enregistrer",
      saved: "Réglages enregistrés",
    },
    fields: {
      choose: "Choisir…",
      noOptions: "Aucune option",
    },
    panel: {
      tooltip: "{{panel}} ({{plugin}})",
      invalidContent: "Le plugin a renvoyé un panneau que cette app ne peut pas afficher.",
      retry: "Réessayer",
      empty: "Rien à afficher.",
      submit: "Envoyer",
      submitted: "Envoyé",
      viewUnsupported: "Cette vue fonctionne sur ordinateur et sur le web.",
      viewNeedsClient: "Installez {{plugin}} sur cet appareil pour ouvrir cette vue.",
      viewFailed: "Impossible d'ouvrir cette vue : {{error}}",
    },
    sessionActions: {
      trigger: "Actions des plugins",
    },
    composerActions: {
      trigger: "Actions des plugins du compositeur",
    },
    commandCenter: {
      section: "Plugins",
    },
  },
  ja: {
    title: "プラグイン",
    disabledByBrand: "このビルドではプラグインが無効になっています。",
    devBadge: "DEV",
    tabs: {
      installed: "インストール済み",
      browse: "探す",
      repositories: "リポジトリ",
    },
    target: {
      label: "インストール先",
      client: "このクライアント",
      host: "ホスト",
      none: "プラグインに対応したホストがありません",
    },
    client: {
      installedEmpty: "このデバイスにインストールされたプラグインはありません。",
      loadFailed: "このデバイスのプラグインを読み込めませんでした: {{error}}",
      unsupported: "クライアントプラグインはデスクトップ版とウェブ版で動作します。",
      addFolder: "ローカルフォルダを追加",
      addFolderHint:
        "このコンピュータのプラグインフォルダをリンクします。リンクしたプラグインは整合性チェックを省略します。",
      linked: "{{name}} をリンクしました。",
      reload: "再読み込み",
      consentTitle: "{{name}} をこのデバイスにインストール",
      consentIntro: "{{name}} はこのデバイスのアプリ内で動作します。要求する権限:",
      sandboxed:
        "アプリのウィンドウ、ストレージ、他のプラグインにアクセスできないサンドボックスで動作します。",
      browseEmpty: "利用できるクライアントプラグインはありません。",
      starting: "起動中",
      hybridInstall: "このデバイスにインストール",
      hybridInstalled: "このデバイスにクライアントコンポーネントをインストール済み",
      hybridUnsupported: "クライアントコンポーネント: デスクトップ版またはウェブ版が必要です。",
      hybridDev:
        "クライアントコンポーネント: デスクトップアプリの「このクライアント」からフォルダをリンクしてください。",
      hybridFailed: "クライアントコンポーネントが失敗しました: {{error}}",
      needsClient:
        "このプラグインの一部はアプリ内で動作します。各デバイスにクライアントコンポーネントをインストールしてください。",
    },
    status: {
      active: "有効",
      disabled: "無効",
      error: "エラー",
      incompatible: "非対応",
      blocked: "ブロック済み",
      inactive: "非アクティブ",
    },
    tier: {
      official: "公式",
      brand: "ブランド",
      user: "ユーザー",
      dev: "ローカル",
    },
    capabilities: {
      network: "ネットワーク通信を行う",
      filesystem_workspace: "ワークスペース内のファイルを読み書きする",
      process_spawn: "ホスト上でプログラムを実行する",
      agent_read: "エージェントのセッションとイベントを読む",
      agent_write: "エージェントにメッセージを送る",
      settings_store: "独自の設定を保存する",
      ui_contribute: "コマンド・ボタン・パネルを追加する",
      rpc: "アプリからのリクエストに応答する",
      ui_view: "アプリ内に独自のビューを表示",
      media_microphone: "マイクを使用",
      media_audio: "音声を再生",
      composer: "入力欄にボタンを追加し、テキストを挿入",
      speech: "ホストの音声認識と音声合成を使用",
    },
    errors: {
      withDetail: "{{summary}} {{detail}}",
      not_found: "見つかりません。",
      invalid_request: "リクエストが不正です。",
      forbidden: "許可されていません。",
      consent_required: "この更新には新しい権限が必要です。",
      signature_invalid: "リポジトリの署名を検証できませんでした。",
      hash_mismatch: "ダウンロードがチェックサムと一致しません。",
      manifest_mismatch: "プラグインがリポジトリの登録内容と一致しません。",
      fetch_failed: "リポジトリからダウンロードできませんでした。",
      incompatible: "このホストには対応していません。",
      already_installed: "すでにインストールされています。",
      plugin_error: "プラグインがエラーを報告しました。",
      not_active: "プラグインが動作していません。",
      timeout: "リクエストがタイムアウトしました。",
      internal: "ホストで問題が発生しました。",
    },
    installed: {
      empty: "このホストにはプラグインがインストールされていません。",
      meta: "{{id}} · v{{version}}",
      enable: "{{name}} を有効にする",
      updateAvailable: "v{{version}} に更新",
      needsClientComponent:
        "このプラグインの一部はアプリ内で動作します。各デバイスにクライアントコンポーネントをインストールしてください。",
      update: "更新",
      settings: "設定",
      unlink: "リンク解除",
      uninstall: "アンインストール",
      uninstallTitle: "{{name}} をアンインストールしますか？",
      uninstallMessage: "{{name}} と保存された設定がこのホストから削除されます。",
    },
    browse: {
      search: "プラグインを検索",
      clearSearch: "検索をクリア",
      retry: "再試行",
      repoFailed: "{{name}} を読み込めませんでした：{{error}}",
      empty: "リポジトリに利用できるプラグインがありません。",
      noMatches: "検索に一致するプラグインはありません。",
      uncategorised: "その他",
      installed: "v{{version}} をインストール済み",
      install: "インストール",
      needsClient: "クライアント部品が必要",
      incompatible: "このホストに対応するバージョンがありません。",
    },
    consent: {
      installTitle: "{{name}} をインストール",
      updateTitle: "{{name}} を更新",
      installIntro: "このプラグインは次の権限を求めています：",
      updateIntro: "この更新は新しい権限を求めています：",
      noCapabilities: "特別な権限はありません。",
      notSandboxed:
        "プラグインはホストのプロセス内で動作し、サンドボックス化されていません。信頼できるプラグインだけをインストールしてください。",
      userRepoWarning:
        "このプラグインは、公式やブランドのリポジトリではなく、ご自身で追加したリポジトリのものです。",
      install: "許可してインストール",
      update: "許可して更新",
    },
    repos: {
      addTitle: "リポジトリを追加",
      url: "インデックス URL",
      name: "名前（任意）",
      publicKey: "公開鍵（任意）",
      publicKeyHint: "空欄にすると、初回追加時にリポジトリが公開している鍵を信頼します。",
      add: "リポジトリを追加",
      remove: "削除",
      count: "プラグイン数：{{count}}",
      key: "鍵：{{key}}",
      pinnedTitle: "{{name}} を追加しました",
      pinnedBody: "固定された署名鍵：{{key}}。公開者が共有した鍵と一致するか確認してください。",
    },
    developer: {
      title: "ローカルプラグイン",
      forbidden: "ローカルプラグインのリンクには daemon のベータ版が必要です。",
      hint: "{{host}} 上のローカルのプラグインフォルダーをリンクできます。リンクしたプラグインは署名チェックをスキップし、変更時に再読み込みされます。",
      addFolder: "ローカルフォルダーを追加",
      path: "フォルダーのパス",
      pathHint: "{{host}} 上のプラグインフォルダーの絶対パス。",
      link: "フォルダーをリンク",
      linked: "{{name}} をリンクしました",
    },
    settings: {
      title: "{{name}} の設定",
      none: "このプラグインには設定がありません。",
      save: "保存",
      saved: "設定を保存しました",
    },
    fields: {
      choose: "選択…",
      noOptions: "選択肢がありません",
    },
    panel: {
      tooltip: "{{panel}}（{{plugin}}）",
      invalidContent: "プラグインがこのアプリで表示できないパネルを返しました。",
      retry: "再試行",
      empty: "表示する内容がありません。",
      submit: "送信",
      submitted: "送信しました",
      viewUnsupported: "このビューはデスクトップと Web で動作します。",
      viewNeedsClient:
        "このビューを開くには、このデバイスに {{plugin}} をインストールしてください。",
      viewFailed: "このビューを開けませんでした: {{error}}",
    },
    sessionActions: {
      trigger: "プラグインのアクション",
    },
    composerActions: {
      trigger: "入力欄のプラグインアクション",
    },
    commandCenter: {
      section: "プラグイン",
    },
  },
  ko: {
    title: "플러그인",
    disabledByBrand: "이 빌드에서는 플러그인이 꺼져 있습니다.",
    devBadge: "DEV",
    tabs: {
      installed: "설치됨",
      browse: "둘러보기",
      repositories: "저장소",
    },
    target: {
      label: "설치 대상",
      client: "이 클라이언트",
      host: "호스트",
      none: "플러그인을 지원하는 호스트가 없습니다",
    },
    client: {
      installedEmpty: "이 기기에 설치된 플러그인이 없습니다.",
      loadFailed: "이 기기의 플러그인을 읽을 수 없습니다: {{error}}",
      unsupported: "클라이언트 플러그인은 데스크톱 및 웹 앱에서 실행됩니다.",
      addFolder: "로컬 폴더 추가",
      addFolderHint:
        "이 컴퓨터의 플러그인 폴더를 연결합니다. 연결된 플러그인은 무결성 검사를 건너뜁니다.",
      linked: "{{name}} 연결됨.",
      reload: "다시 불러오기",
      consentTitle: "이 기기에 {{name}} 설치",
      consentIntro: "{{name}}은(는) 이 기기의 앱 안에서 실행됩니다. 요청 권한:",
      sandboxed: "앱의 창, 저장소, 다른 플러그인에 접근할 수 없는 샌드박스에서 실행됩니다.",
      browseEmpty: "사용 가능한 클라이언트 플러그인이 없습니다.",
      starting: "시작 중",
      hybridInstall: "이 기기에 설치",
      hybridInstalled: "이 기기에 클라이언트 구성 요소가 설치됨",
      hybridUnsupported: "클라이언트 구성 요소: 데스크톱 또는 웹 앱이 필요합니다.",
      hybridDev: "클라이언트 구성 요소: 데스크톱 앱의 이 클라이언트에서 폴더를 연결하세요.",
      hybridFailed: "클라이언트 구성 요소 실패: {{error}}",
      needsClient:
        "이 플러그인의 일부는 앱에서 실행됩니다. 각 기기에 클라이언트 구성 요소를 설치하세요.",
    },
    status: {
      active: "활성",
      disabled: "비활성화됨",
      error: "오류",
      incompatible: "호환되지 않음",
      blocked: "차단됨",
      inactive: "비활성",
    },
    tier: {
      official: "공식",
      brand: "브랜드",
      user: "사용자",
      dev: "로컬",
    },
    capabilities: {
      network: "네트워크 요청 보내기",
      filesystem_workspace: "워크스페이스의 파일 읽기 및 쓰기",
      process_spawn: "호스트에서 프로그램 실행",
      agent_read: "에이전트 세션과 이벤트 읽기",
      agent_write: "에이전트에 메시지 보내기",
      settings_store: "자체 설정 저장",
      ui_contribute: "명령, 버튼, 패널 추가",
      rpc: "앱의 요청에 응답",
      ui_view: "앱에 자체 보기 표시",
      media_microphone: "마이크 사용",
      media_audio: "오디오 재생",
      composer: "작성기에 버튼 추가 및 텍스트 삽입",
      speech: "호스트의 음성 인식과 음성 사용",
    },
    errors: {
      withDetail: "{{summary}} {{detail}}",
      not_found: "찾을 수 없습니다.",
      invalid_request: "요청이 올바르지 않습니다.",
      forbidden: "허용되지 않습니다.",
      consent_required: "이 업데이트에는 새 권한이 필요합니다.",
      signature_invalid: "저장소 서명을 확인하지 못했습니다.",
      hash_mismatch: "다운로드가 체크섬과 일치하지 않습니다.",
      manifest_mismatch: "플러그인이 저장소 항목과 일치하지 않습니다.",
      fetch_failed: "저장소에서 다운로드하지 못했습니다.",
      incompatible: "이 호스트와 호환되지 않습니다.",
      already_installed: "이미 설치되어 있습니다.",
      plugin_error: "플러그인이 오류를 보고했습니다.",
      not_active: "플러그인이 실행 중이 아닙니다.",
      timeout: "요청 시간이 초과되었습니다.",
      internal: "호스트에서 문제가 발생했습니다.",
    },
    installed: {
      empty: "이 호스트에 설치된 플러그인이 없습니다.",
      meta: "{{id}} · v{{version}}",
      enable: "{{name}} 사용",
      updateAvailable: "v{{version}}(으)로 업데이트",
      needsClientComponent:
        "이 플러그인의 일부는 앱에서 실행됩니다. 각 기기에 클라이언트 구성 요소를 설치하세요.",
      update: "업데이트",
      settings: "설정",
      unlink: "연결 해제",
      uninstall: "제거",
      uninstallTitle: "{{name}}을(를) 제거할까요?",
      uninstallMessage: "{{name}}과(와) 저장된 설정이 이 호스트에서 제거됩니다.",
    },
    browse: {
      search: "플러그인 검색",
      clearSearch: "검색 지우기",
      retry: "다시 시도",
      repoFailed: "{{name}}을(를) 불러오지 못했습니다: {{error}}",
      empty: "저장소에 사용할 수 있는 플러그인이 없습니다.",
      noMatches: "검색과 일치하는 플러그인이 없습니다.",
      uncategorised: "기타",
      installed: "v{{version}} 설치됨",
      install: "설치",
      needsClient: "클라이언트 구성 요소 필요",
      incompatible: "이 호스트와 호환되는 버전이 없습니다.",
    },
    consent: {
      installTitle: "{{name}} 설치",
      updateTitle: "{{name}} 업데이트",
      installIntro: "이 플러그인은 다음 권한을 요청합니다:",
      updateIntro: "이 업데이트는 새 권한을 요청합니다:",
      noCapabilities: "특별한 권한이 없습니다.",
      notSandboxed:
        "플러그인은 호스트 프로세스 안에서 실행되며 샌드박스로 격리되지 않습니다. 신뢰하는 플러그인만 설치하세요.",
      userRepoWarning:
        "이 플러그인은 공식 또는 브랜드 저장소가 아니라 직접 추가한 저장소에서 왔습니다.",
      install: "허용하고 설치",
      update: "허용하고 업데이트",
    },
    repos: {
      addTitle: "저장소 추가",
      url: "인덱스 URL",
      name: "이름(선택)",
      publicKey: "공개 키(선택)",
      publicKeyHint: "비워 두면 처음 추가할 때 저장소가 게시한 키를 신뢰합니다.",
      add: "저장소 추가",
      remove: "삭제",
      count: "플러그인: {{count}}",
      key: "키: {{key}}",
      pinnedTitle: "{{name}} 추가됨",
      pinnedBody: "고정된 서명 키: {{key}}. 게시자가 공유한 키와 일치하는지 확인하세요.",
    },
    developer: {
      title: "로컬 플러그인",
      forbidden: "로컬 플러그인을 연결하려면 daemon 베타 빌드가 필요합니다.",
      hint: "{{host}}의 로컬 플러그인 폴더를 연결할 수 있습니다. 연결된 플러그인은 서명 검사를 건너뛰고 변경 시 다시 로드됩니다.",
      addFolder: "로컬 폴더 추가",
      path: "폴더 경로",
      pathHint: "{{host}}에 있는 플러그인 폴더의 절대 경로입니다.",
      link: "폴더 연결",
      linked: "{{name}} 연결됨",
    },
    settings: {
      title: "{{name}} 설정",
      none: "이 플러그인에는 설정이 없습니다.",
      save: "저장",
      saved: "설정이 저장되었습니다",
    },
    fields: {
      choose: "선택…",
      noOptions: "옵션 없음",
    },
    panel: {
      tooltip: "{{panel}} ({{plugin}})",
      invalidContent: "플러그인이 이 앱에서 표시할 수 없는 패널을 반환했습니다.",
      retry: "다시 시도",
      empty: "표시할 내용이 없습니다.",
      submit: "제출",
      submitted: "제출됨",
      viewUnsupported: "이 보기는 데스크톱과 웹에서 실행됩니다.",
      viewNeedsClient: "이 보기를 열려면 이 기기에 {{plugin}}을(를) 설치하세요.",
      viewFailed: "이 보기를 열 수 없습니다: {{error}}",
    },
    sessionActions: {
      trigger: "플러그인 작업",
    },
    composerActions: {
      trigger: "작성기 플러그인 작업",
    },
    commandCenter: {
      section: "플러그인",
    },
  },
  "pt-BR": {
    title: "Plugins",
    disabledByBrand: "Os plugins estão desativados nesta versão.",
    devBadge: "DEV",
    tabs: {
      installed: "Instalados",
      browse: "Explorar",
      repositories: "Repositórios",
    },
    target: {
      label: "Instalar em",
      client: "Este cliente",
      host: "Host",
      none: "Nenhum host oferece suporte a plugins",
    },
    client: {
      installedEmpty: "Nenhum plugin instalado neste dispositivo.",
      loadFailed: "Não foi possível ler os plugins deste dispositivo: {{error}}",
      unsupported: "Plugins de cliente funcionam nos apps desktop e web.",
      addFolder: "Adicionar pasta local",
      addFolderHint:
        "Vincule uma pasta de plugin deste computador. Plugins vinculados ignoram as verificações de integridade.",
      linked: "{{name}} vinculado.",
      reload: "Recarregar",
      consentTitle: "Instalar {{name}} neste dispositivo",
      consentIntro: "{{name}} roda dentro deste app neste dispositivo. Ele pede para:",
      sandboxed:
        "Ele roda em uma sandbox sem acesso às janelas, ao armazenamento ou a outros plugins do app.",
      browseEmpty: "Nenhum plugin de cliente disponível.",
      starting: "Iniciando",
      hybridInstall: "Instalar neste dispositivo",
      hybridInstalled: "Componente de cliente instalado neste dispositivo",
      hybridUnsupported: "Componente de cliente: requer o app desktop ou web.",
      hybridDev: "Componente de cliente: vincule a pasta em Este cliente no app desktop.",
      hybridFailed: "Falha no componente de cliente: {{error}}",
      needsClient:
        "Parte deste plugin roda no app: instale o componente de cliente em cada dispositivo.",
    },
    status: {
      active: "Ativo",
      disabled: "Desativado",
      error: "Erro",
      incompatible: "Incompatível",
      blocked: "Bloqueado",
      inactive: "Inativo",
    },
    tier: {
      official: "Oficial",
      brand: "Marca",
      user: "Usuário",
      dev: "Local",
    },
    capabilities: {
      network: "Fazer requisições de rede",
      filesystem_workspace: "Ler e gravar arquivos nos espaços de trabalho",
      process_spawn: "Executar programas no host",
      agent_read: "Ler sessões de agentes e seus eventos",
      agent_write: "Enviar mensagens aos agentes",
      settings_store: "Guardar as próprias configurações",
      ui_contribute: "Adicionar comandos, botões e painéis",
      rpc: "Responder a requisições do app",
      ui_view: "Mostrar as próprias visualizações no app",
      media_microphone: "Usar o microfone",
      media_audio: "Reproduzir áudio",
      composer: "Adicionar botões ao editor e inserir texto",
      speech: "Usar o reconhecimento de fala e as vozes do host",
    },
    errors: {
      withDetail: "{{summary}} {{detail}}",
      not_found: "Não encontrado.",
      invalid_request: "A requisição era inválida.",
      forbidden: "Não permitido.",
      consent_required: "Esta atualização precisa de novas permissões.",
      signature_invalid: "Não foi possível verificar a assinatura do repositório.",
      hash_mismatch: "O download não corresponde à soma de verificação.",
      manifest_mismatch: "O plugin não corresponde à entrada no repositório.",
      fetch_failed: "Não foi possível baixar do repositório.",
      incompatible: "Não é compatível com este host.",
      already_installed: "Já instalado.",
      plugin_error: "O plugin informou um erro.",
      not_active: "O plugin não está em execução.",
      timeout: "A requisição expirou.",
      internal: "Algo deu errado no host.",
    },
    installed: {
      empty: "Nenhum plugin instalado neste host.",
      meta: "{{id}} · v{{version}}",
      enable: "Ativar {{name}}",
      updateAvailable: "Atualizar para v{{version}}",
      needsClientComponent:
        "Parte deste plugin roda no app: instale o componente de cliente em cada dispositivo.",
      update: "Atualizar",
      settings: "Configurações",
      unlink: "Desvincular",
      uninstall: "Desinstalar",
      uninstallTitle: "Desinstalar {{name}}?",
      uninstallMessage: "{{name}} e suas configurações salvas serão removidos deste host.",
    },
    browse: {
      search: "Buscar plugins",
      clearSearch: "Limpar busca",
      retry: "Tentar novamente",
      repoFailed: "Não foi possível carregar {{name}}: {{error}}",
      empty: "Nenhum plugin disponível nos seus repositórios.",
      noMatches: "Nenhum plugin corresponde à busca.",
      uncategorised: "Outros",
      installed: "v{{version}} instalada",
      install: "Instalar",
      needsClient: "Precisa de componente de cliente",
      incompatible: "Nenhuma versão é compatível com este host.",
    },
    consent: {
      installTitle: "Instalar {{name}}",
      updateTitle: "Atualizar {{name}}",
      installIntro: "Este plugin pede as seguintes permissões:",
      updateIntro: "Esta atualização pede novas permissões:",
      noCapabilities: "Nenhuma permissão especial.",
      notSandboxed:
        "Plugins rodam dentro do processo do host e não ficam isolados. Instale apenas plugins em que você confia.",
      userRepoWarning:
        "Este plugin vem de um repositório que você mesmo adicionou, não de um repositório oficial ou da marca.",
      install: "Permitir e instalar",
      update: "Permitir e atualizar",
    },
    repos: {
      addTitle: "Adicionar repositório",
      url: "URL do índice",
      name: "Nome (opcional)",
      publicKey: "Chave pública (opcional)",
      publicKeyHint:
        "Deixe em branco para confiar na chave que o repositório publica na primeira vez que você o adiciona.",
      add: "Adicionar repositório",
      remove: "Remover",
      count: "Plugins: {{count}}",
      key: "Chave: {{key}}",
      pinnedTitle: "{{name}} adicionado",
      pinnedBody:
        "Chave de assinatura fixada: {{key}}. Confira se corresponde à que o publicador compartilhou.",
    },
    developer: {
      title: "Plugins locais",
      forbidden: "Vincular plugins locais requer uma versão beta do daemon.",
      hint: "Permite vincular pastas de plugins locais em {{host}}. Plugins vinculados ignoram a verificação de assinatura e recarregam ao mudar.",
      addFolder: "Adicionar pasta local",
      path: "Caminho da pasta",
      pathHint: "Caminho absoluto da pasta do plugin em {{host}}.",
      link: "Vincular pasta",
      linked: "{{name}} vinculado",
    },
    settings: {
      title: "Configurações de {{name}}",
      none: "Este plugin não tem configurações.",
      save: "Salvar",
      saved: "Configurações salvas",
    },
    fields: {
      choose: "Escolher…",
      noOptions: "Sem opções",
    },
    panel: {
      tooltip: "{{panel}} ({{plugin}})",
      invalidContent: "O plugin retornou um painel que este app não consegue exibir.",
      retry: "Tentar novamente",
      empty: "Nada para mostrar.",
      submit: "Enviar",
      submitted: "Enviado",
      viewUnsupported: "Esta visualização funciona no desktop e na web.",
      viewNeedsClient: "Instale {{plugin}} neste dispositivo para abrir esta visualização.",
      viewFailed: "Não foi possível abrir esta visualização: {{error}}",
    },
    sessionActions: {
      trigger: "Ações de plugins",
    },
    composerActions: {
      trigger: "Ações de plugins do editor",
    },
    commandCenter: {
      section: "Plugins",
    },
  },
  ru: {
    title: "Плагины",
    disabledByBrand: "Плагины отключены в этой сборке.",
    devBadge: "DEV",
    tabs: {
      installed: "Установленные",
      browse: "Обзор",
      repositories: "Репозитории",
    },
    target: {
      label: "Установить на",
      client: "Этот клиент",
      host: "Хост",
      none: "Нет хостов с поддержкой плагинов",
    },
    client: {
      installedEmpty: "На этом устройстве нет установленных плагинов.",
      loadFailed: "Не удалось прочитать плагины этого устройства: {{error}}",
      unsupported: "Клиентские плагины работают в настольном и веб-приложении.",
      addFolder: "Добавить локальную папку",
      addFolderHint:
        "Подключите папку плагина на этом компьютере. Подключённые плагины не проходят проверку целостности.",
      linked: "{{name}} подключён.",
      reload: "Перезагрузить",
      consentTitle: "Установить {{name}} на это устройство",
      consentIntro: "{{name}} работает внутри приложения на этом устройстве. Запрашивает:",
      sandboxed:
        "Работает в песочнице без доступа к окнам, хранилищу и другим плагинам приложения.",
      browseEmpty: "Нет доступных клиентских плагинов.",
      starting: "Запуск",
      hybridInstall: "Установить на это устройство",
      hybridInstalled: "Клиентский компонент установлен на этом устройстве",
      hybridUnsupported: "Клиентский компонент: нужно настольное или веб-приложение.",
      hybridDev:
        "Клиентский компонент: подключите его папку в разделе «Этот клиент» настольного приложения.",
      hybridFailed: "Ошибка клиентского компонента: {{error}}",
      needsClient:
        "Часть плагина работает в приложении: установите клиентский компонент на каждом устройстве.",
    },
    status: {
      active: "Активен",
      disabled: "Отключён",
      error: "Ошибка",
      incompatible: "Несовместим",
      blocked: "Заблокирован",
      inactive: "Неактивен",
    },
    tier: {
      official: "Официальный",
      brand: "Бренд",
      user: "Пользовательский",
      dev: "Локальный",
    },
    capabilities: {
      network: "Выполнять сетевые запросы",
      filesystem_workspace: "Читать и записывать файлы в рабочих пространствах",
      process_spawn: "Запускать программы на хосте",
      agent_read: "Читать сессии агентов и их события",
      agent_write: "Отправлять сообщения агентам",
      settings_store: "Хранить собственные настройки",
      ui_contribute: "Добавлять команды, кнопки и панели",
      rpc: "Отвечать на запросы приложения",
      ui_view: "Показывать собственные представления в приложении",
      media_microphone: "Использовать микрофон",
      media_audio: "Воспроизводить звук",
      composer: "Добавлять кнопки в редактор и вставлять текст",
      speech: "Использовать распознавание речи и голоса хоста",
    },
    errors: {
      withDetail: "{{summary}} {{detail}}",
      not_found: "Не найдено.",
      invalid_request: "Некорректный запрос.",
      forbidden: "Не разрешено.",
      consent_required: "Для этого обновления нужны новые разрешения.",
      signature_invalid: "Не удалось проверить подпись репозитория.",
      hash_mismatch: "Загруженный файл не совпадает с контрольной суммой.",
      manifest_mismatch: "Плагин не совпадает со своей записью в репозитории.",
      fetch_failed: "Не удалось загрузить из репозитория.",
      incompatible: "Несовместимо с этим хостом.",
      already_installed: "Уже установлен.",
      plugin_error: "Плагин сообщил об ошибке.",
      not_active: "Плагин не запущен.",
      timeout: "Время ожидания запроса истекло.",
      internal: "На хосте что-то пошло не так.",
    },
    installed: {
      empty: "На этом хосте нет установленных плагинов.",
      meta: "{{id}} · v{{version}}",
      enable: "Включить {{name}}",
      updateAvailable: "Обновить до v{{version}}",
      needsClientComponent:
        "Часть плагина работает в приложении: установите клиентский компонент на каждом устройстве.",
      update: "Обновить",
      settings: "Настройки",
      unlink: "Отвязать",
      uninstall: "Удалить",
      uninstallTitle: "Удалить {{name}}?",
      uninstallMessage: "{{name}} и его сохранённые настройки будут удалены с этого хоста.",
    },
    browse: {
      search: "Поиск плагинов",
      clearSearch: "Очистить поиск",
      retry: "Повторить",
      repoFailed: "Не удалось загрузить {{name}}: {{error}}",
      empty: "В ваших репозиториях нет доступных плагинов.",
      noMatches: "Нет плагинов, подходящих под запрос.",
      uncategorised: "Другое",
      installed: "Установлена v{{version}}",
      install: "Установить",
      needsClient: "Нужен клиентский компонент",
      incompatible: "Нет версии, совместимой с этим хостом.",
    },
    consent: {
      installTitle: "Установка {{name}}",
      updateTitle: "Обновление {{name}}",
      installIntro: "Плагин запрашивает следующие разрешения:",
      updateIntro: "Обновление запрашивает новые разрешения:",
      noCapabilities: "Особых разрешений нет.",
      notSandboxed:
        "Плагины работают внутри процесса хоста и не изолированы. Устанавливайте только те плагины, которым доверяете.",
      userRepoWarning:
        "Этот плагин из репозитория, который вы добавили сами, а не из официального репозитория или репозитория бренда.",
      install: "Разрешить и установить",
      update: "Разрешить и обновить",
    },
    repos: {
      addTitle: "Добавить репозиторий",
      url: "URL индекса",
      name: "Название (необязательно)",
      publicKey: "Открытый ключ (необязательно)",
      publicKeyHint:
        "Оставьте пустым, чтобы доверять ключу, который репозиторий публикует при первом добавлении.",
      add: "Добавить репозиторий",
      remove: "Убрать",
      count: "Плагинов: {{count}}",
      key: "Ключ: {{key}}",
      pinnedTitle: "{{name}} добавлен",
      pinnedBody:
        "Закреплённый ключ подписи: {{key}}. Убедитесь, что он совпадает с ключом, который сообщил издатель.",
    },
    developer: {
      title: "Локальные плагины",
      forbidden: "Для подключения локальных плагинов нужна бета-сборка daemon.",
      hint: "Позволяет привязывать локальные папки плагинов на {{host}}. Привязанные плагины пропускают проверку подписи и перезагружаются при изменениях.",
      addFolder: "Добавить локальную папку",
      path: "Путь к папке",
      pathHint: "Абсолютный путь к папке плагина на {{host}}.",
      link: "Привязать папку",
      linked: "{{name}} привязан",
    },
    settings: {
      title: "Настройки {{name}}",
      none: "У этого плагина нет настроек.",
      save: "Сохранить",
      saved: "Настройки сохранены",
    },
    fields: {
      choose: "Выбрать…",
      noOptions: "Нет вариантов",
    },
    panel: {
      tooltip: "{{panel}} ({{plugin}})",
      invalidContent: "Плагин вернул панель, которую это приложение не может показать.",
      retry: "Повторить",
      empty: "Нечего показать.",
      submit: "Отправить",
      submitted: "Отправлено",
      viewUnsupported: "Это представление работает в настольной и веб-версии.",
      viewNeedsClient: "Установите {{plugin}} на это устройство, чтобы открыть это представление.",
      viewFailed: "Не удалось открыть представление: {{error}}",
    },
    sessionActions: {
      trigger: "Действия плагинов",
    },
    composerActions: {
      trigger: "Действия плагинов в редакторе",
    },
    commandCenter: {
      section: "Плагины",
    },
  },
  "zh-CN": {
    title: "插件",
    disabledByBrand: "此版本已关闭插件功能。",
    devBadge: "DEV",
    tabs: {
      installed: "已安装",
      browse: "浏览",
      repositories: "仓库",
    },
    target: {
      label: "安装到",
      client: "此客户端",
      host: "主机",
      none: "没有支持插件的主机",
    },
    client: {
      installedEmpty: "此设备上未安装插件。",
      loadFailed: "无法读取此设备的插件：{{error}}",
      unsupported: "客户端插件在桌面版和网页版中运行。",
      addFolder: "添加本地文件夹",
      addFolderHint: "链接此电脑上的插件文件夹。链接的插件会跳过完整性检查。",
      linked: "已链接 {{name}}。",
      reload: "重新加载",
      consentTitle: "在此设备上安装 {{name}}",
      consentIntro: "{{name}} 在此设备的应用内运行。它请求：",
      sandboxed: "它在沙箱中运行，无法访问应用的窗口、存储或其他插件。",
      browseEmpty: "没有可用的客户端插件。",
      starting: "正在启动",
      hybridInstall: "在此设备上安装",
      hybridInstalled: "已在此设备上安装客户端组件",
      hybridUnsupported: "客户端组件：需要桌面版或网页版。",
      hybridDev: "客户端组件：请在桌面应用的“此客户端”中链接其文件夹。",
      hybridFailed: "客户端组件失败：{{error}}",
      needsClient: "此插件的一部分在应用内运行：请在每台设备上安装其客户端组件。",
    },
    status: {
      active: "运行中",
      disabled: "已停用",
      error: "错误",
      incompatible: "不兼容",
      blocked: "已阻止",
      inactive: "未激活",
    },
    tier: {
      official: "官方",
      brand: "品牌",
      user: "用户",
      dev: "本地",
    },
    capabilities: {
      network: "发起网络请求",
      filesystem_workspace: "读写工作区中的文件",
      process_spawn: "在主机上运行程序",
      agent_read: "读取智能体会话及其事件",
      agent_write: "向智能体发送消息",
      settings_store: "保存自己的设置",
      ui_contribute: "添加命令、按钮和面板",
      rpc: "响应来自应用的请求",
      ui_view: "在应用中显示自己的视图",
      media_microphone: "使用麦克风",
      media_audio: "播放音频",
      composer: "添加输入框按钮并插入文本",
      speech: "使用主机的语音识别和语音",
    },
    errors: {
      withDetail: "{{summary}} {{detail}}",
      not_found: "未找到。",
      invalid_request: "请求无效。",
      forbidden: "不允许。",
      consent_required: "此更新需要新的权限。",
      signature_invalid: "无法验证仓库签名。",
      hash_mismatch: "下载内容与校验和不一致。",
      manifest_mismatch: "插件与其仓库条目不一致。",
      fetch_failed: "无法从仓库下载。",
      incompatible: "与此主机不兼容。",
      already_installed: "已经安装。",
      plugin_error: "插件报告了错误。",
      not_active: "插件未在运行。",
      timeout: "请求超时。",
      internal: "主机上出现问题。",
    },
    installed: {
      empty: "此主机上没有安装插件。",
      meta: "{{id}} · v{{version}}",
      enable: "启用 {{name}}",
      updateAvailable: "更新到 v{{version}}",
      needsClientComponent: "此插件的一部分在应用内运行：请在每台设备上安装其客户端组件。",
      update: "更新",
      settings: "设置",
      unlink: "取消链接",
      uninstall: "卸载",
      uninstallTitle: "卸载 {{name}}？",
      uninstallMessage: "{{name}} 及其保存的设置将从此主机中移除。",
    },
    browse: {
      search: "搜索插件",
      clearSearch: "清除搜索",
      retry: "重试",
      repoFailed: "无法加载 {{name}}：{{error}}",
      empty: "你的仓库中没有可用插件。",
      noMatches: "没有与搜索匹配的插件。",
      uncategorised: "其他",
      installed: "已安装 v{{version}}",
      install: "安装",
      needsClient: "需要客户端组件",
      incompatible: "没有与此主机兼容的版本。",
    },
    consent: {
      installTitle: "安装 {{name}}",
      updateTitle: "更新 {{name}}",
      installIntro: "此插件请求以下权限：",
      updateIntro: "此更新请求新的权限：",
      noCapabilities: "无特殊权限。",
      notSandboxed: "插件在主机进程中运行，没有沙箱隔离。请只安装你信任的插件。",
      userRepoWarning: "此插件来自你自行添加的仓库，而不是官方或品牌仓库。",
      install: "允许并安装",
      update: "允许并更新",
    },
    repos: {
      addTitle: "添加仓库",
      url: "索引 URL",
      name: "名称（可选）",
      publicKey: "公钥（可选）",
      publicKeyHint: "留空则在首次添加时信任仓库发布的密钥。",
      add: "添加仓库",
      remove: "移除",
      count: "插件数：{{count}}",
      key: "密钥：{{key}}",
      pinnedTitle: "已添加 {{name}}",
      pinnedBody: "已固定的签名密钥：{{key}}。请确认它与发布者提供的密钥一致。",
    },
    developer: {
      title: "本地插件",
      forbidden: "链接本地插件需要 daemon 的测试版。",
      hint: "允许链接 {{host}} 上的本地插件文件夹。已链接的插件跳过签名检查，并在更改时重新加载。",
      addFolder: "添加本地文件夹",
      path: "文件夹路径",
      pathHint: "{{host}} 上插件文件夹的绝对路径。",
      link: "链接文件夹",
      linked: "已链接 {{name}}",
    },
    settings: {
      title: "{{name}} 设置",
      none: "此插件没有设置。",
      save: "保存",
      saved: "设置已保存",
    },
    fields: {
      choose: "选择…",
      noOptions: "没有选项",
    },
    panel: {
      tooltip: "{{panel}}（{{plugin}}）",
      invalidContent: "插件返回了此应用无法显示的面板。",
      retry: "重试",
      empty: "没有可显示的内容。",
      submit: "提交",
      submitted: "已提交",
      viewUnsupported: "此视图可在桌面版和网页版中运行。",
      viewNeedsClient: "在此设备上安装 {{plugin}} 以打开此视图。",
      viewFailed: "无法打开此视图：{{error}}",
    },
    sessionActions: {
      trigger: "插件操作",
    },
    composerActions: {
      trigger: "输入框插件操作",
    },
    commandCenter: {
      section: "插件",
    },
  },
  ar: {
    title: "الإضافات",
    disabledByBrand: "الإضافات معطّلة في هذا الإصدار.",
    devBadge: "DEV",
    tabs: {
      installed: "المثبّتة",
      browse: "تصفّح",
      repositories: "المستودعات",
    },
    target: {
      label: "التثبيت على",
      client: "هذا العميل",
      host: "المضيف",
      none: "لا يوجد مضيف يدعم الإضافات",
    },
    client: {
      installedEmpty: "لا توجد إضافات مثبتة على هذا الجهاز.",
      loadFailed: "تعذرت قراءة إضافات هذا الجهاز: {{error}}",
      unsupported: "تعمل إضافات العميل في تطبيقي سطح المكتب والويب.",
      addFolder: "إضافة مجلد محلي",
      addFolderHint: "اربط مجلد إضافة على هذا الحاسوب. تتخطى الإضافات المرتبطة فحوص السلامة.",
      linked: "تم ربط {{name}}.",
      reload: "إعادة التحميل",
      consentTitle: "تثبيت {{name}} على هذا الجهاز",
      consentIntro: "تعمل {{name}} داخل هذا التطبيق على هذا الجهاز. وتطلب:",
      sandboxed: "تعمل في بيئة معزولة دون وصول إلى نوافذ التطبيق أو تخزينه أو الإضافات الأخرى.",
      browseEmpty: "لا توجد إضافات عميل متاحة.",
      starting: "جارٍ البدء",
      hybridInstall: "تثبيت على هذا الجهاز",
      hybridInstalled: "مكوّن العميل مثبت على هذا الجهاز",
      hybridUnsupported: "مكوّن العميل: يتطلب تطبيق سطح المكتب أو الويب.",
      hybridDev: "مكوّن العميل: اربط مجلده من «هذا العميل» في تطبيق سطح المكتب.",
      hybridFailed: "فشل مكوّن العميل: {{error}}",
      needsClient: "يعمل جزء من هذه الإضافة داخل التطبيق: ثبّت مكوّن العميل على كل جهاز.",
    },
    status: {
      active: "نشطة",
      disabled: "معطّلة",
      error: "خطأ",
      incompatible: "غير متوافقة",
      blocked: "محظورة",
      inactive: "غير نشطة",
    },
    tier: {
      official: "رسمي",
      brand: "العلامة",
      user: "المستخدم",
      dev: "محلي",
    },
    capabilities: {
      network: "إرسال طلبات شبكة",
      filesystem_workspace: "قراءة الملفات وكتابتها في مساحات العمل",
      process_spawn: "تشغيل برامج على المضيف",
      agent_read: "قراءة جلسات الوكلاء وأحداثها",
      agent_write: "إرسال رسائل إلى الوكلاء",
      settings_store: "حفظ إعداداتها الخاصة",
      ui_contribute: "إضافة أوامر وأزرار ولوحات",
      rpc: "الرد على طلبات التطبيق",
      ui_view: "عرض واجهاته الخاصة في التطبيق",
      media_microphone: "استخدام الميكروفون",
      media_audio: "تشغيل الصوت",
      composer: "إضافة أزرار إلى المحرر وإدراج نص",
      speech: "استخدام التعرف على الكلام والأصوات في المضيف",
    },
    errors: {
      withDetail: "{{summary}} {{detail}}",
      not_found: "غير موجود.",
      invalid_request: "الطلب غير صالح.",
      forbidden: "غير مسموح.",
      consent_required: "يحتاج هذا التحديث إلى أذونات جديدة.",
      signature_invalid: "تعذّر التحقق من توقيع المستودع.",
      hash_mismatch: "لا يطابق التنزيل مجموع التحقق.",
      manifest_mismatch: "لا تطابق الإضافة إدخالها في المستودع.",
      fetch_failed: "تعذّر التنزيل من المستودع.",
      incompatible: "غير متوافقة مع هذا المضيف.",
      already_installed: "مثبّتة بالفعل.",
      plugin_error: "أبلغت الإضافة عن خطأ.",
      not_active: "الإضافة لا تعمل.",
      timeout: "انتهت مهلة الطلب.",
      internal: "حدث خطأ على المضيف.",
    },
    installed: {
      empty: "لا توجد إضافات مثبّتة على هذا المضيف.",
      meta: "{{id}} · v{{version}}",
      enable: "تفعيل {{name}}",
      updateAvailable: "التحديث إلى v{{version}}",
      needsClientComponent: "يعمل جزء من هذه الإضافة داخل التطبيق: ثبّت مكوّن العميل على كل جهاز.",
      update: "تحديث",
      settings: "الإعدادات",
      unlink: "إلغاء الربط",
      uninstall: "إلغاء التثبيت",
      uninstallTitle: "إلغاء تثبيت {{name}}؟",
      uninstallMessage: "ستُزال {{name}} وإعداداتها المحفوظة من هذا المضيف.",
    },
    browse: {
      search: "ابحث عن إضافات",
      clearSearch: "مسح البحث",
      retry: "إعادة المحاولة",
      repoFailed: "تعذّر تحميل {{name}}: {{error}}",
      empty: "لا توجد إضافات متاحة في مستودعاتك.",
      noMatches: "لا توجد إضافات تطابق البحث.",
      uncategorised: "أخرى",
      installed: "مثبّت v{{version}}",
      install: "تثبيت",
      needsClient: "تحتاج إلى مكوّن للعميل",
      incompatible: "لا يوجد إصدار متوافق مع هذا المضيف.",
    },
    consent: {
      installTitle: "تثبيت {{name}}",
      updateTitle: "تحديث {{name}}",
      installIntro: "تطلب هذه الإضافة الأذونات التالية:",
      updateIntro: "يطلب هذا التحديث أذونات جديدة:",
      noCapabilities: "لا أذونات خاصة.",
      notSandboxed: "تعمل الإضافات داخل عملية المضيف وليست معزولة. ثبّت فقط الإضافات التي تثق بها.",
      userRepoWarning: "هذه الإضافة من مستودع أضفته بنفسك، وليست من مستودع رسمي أو مستودع العلامة.",
      install: "السماح والتثبيت",
      update: "السماح والتحديث",
    },
    repos: {
      addTitle: "إضافة مستودع",
      url: "رابط الفهرس",
      name: "الاسم (اختياري)",
      publicKey: "المفتاح العام (اختياري)",
      publicKeyHint: "اتركه فارغًا للوثوق بالمفتاح الذي ينشره المستودع عند إضافته أول مرة.",
      add: "إضافة المستودع",
      remove: "إزالة",
      count: "الإضافات: {{count}}",
      key: "المفتاح: {{key}}",
      pinnedTitle: "تمت إضافة {{name}}",
      pinnedBody: "مفتاح التوقيع المثبّت: {{key}}. تحقّق من أنه يطابق المفتاح الذي شاركه الناشر.",
    },
    developer: {
      title: "إضافات محلية",
      forbidden: "يتطلب ربط الإضافات المحلية إصدارًا تجريبيًا من daemon.",
      hint: "يتيح ربط مجلدات إضافات محلية على {{host}}. تتخطى الإضافات المرتبطة فحص التوقيع وتُعاد تحميلها عند التغيير.",
      addFolder: "إضافة مجلد محلي",
      path: "مسار المجلد",
      pathHint: "المسار المطلق لمجلد الإضافة على {{host}}.",
      link: "ربط المجلد",
      linked: "تم ربط {{name}}",
    },
    settings: {
      title: "إعدادات {{name}}",
      none: "لا توجد إعدادات لهذه الإضافة.",
      save: "حفظ",
      saved: "تم حفظ الإعدادات",
    },
    fields: {
      choose: "اختر…",
      noOptions: "لا خيارات",
    },
    panel: {
      tooltip: "{{panel}} ({{plugin}})",
      invalidContent: "أعادت الإضافة لوحة لا يستطيع هذا التطبيق عرضها.",
      retry: "إعادة المحاولة",
      empty: "لا شيء لعرضه.",
      submit: "إرسال",
      submitted: "تم الإرسال",
      viewUnsupported: "تعمل هذه الواجهة على سطح المكتب والويب.",
      viewNeedsClient: "ثبّت {{plugin}} على هذا الجهاز لفتح هذه الواجهة.",
      viewFailed: "تعذّر فتح هذه الواجهة: {{error}}",
    },
    sessionActions: {
      trigger: "إجراءات الإضافات",
    },
    composerActions: {
      trigger: "إجراءات المكونات الإضافية في المحرر",
    },
    commandCenter: {
      section: "الإضافات",
    },
  },
};
