const en = {
  exportsDirectory: "Exported conversation directory on {{host}} (optional)",
  title: "Import project and conversations",
  description: "Bring a project and its conversations into {{brandName}}",
  daemon: "On {{host}}",
  computer: "This computer",
  source: "Conversation source",
  destination: "Project directory on {{host}}",
  hint: "Use an existing directory to merge conversations, or a new directory to transfer project files. Existing code is never overwritten.",
  code: "Choose project files",
  conversations: "Choose Claude or Codex JSONL conversations",
  files: "{{count}} files selected",
  history:
    "Uploaded conversations are text history only. They cannot resume the original provider session. Tool calls and attachments are not imported.",
  native: "Daemon conversations use the provider's native session import.",
  preview: "Preview import",
  import: "Import selected",
  cancel: "Cancel",
  close: "Close",
  busy: "Working…",
  progress: "Uploading {{done}} / {{total}} bytes",
  empty: "No importable conversations found for this directory.",
  resumable: "Provider session",
  transcript: "Text history",
  complete: "Import finished",
  imported: "{{count}} conversations imported or already present",
  failures: "Some conversations could not be imported. You can retry the remaining items.",
  saved: "Saved imported conversations",
  more: "Load more",
  back: "Back",
  localUnavailable:
    "Local directory import is available in the desktop or web app. You can import from the daemon here.",
};
type Copy = { [K in keyof typeof en]: string };
export const projectImportCopies: Record<string, Copy> & { en: Copy } = {
  en,
  es: {
    exportsDirectory: "Directorio de conversaciones exportadas en {{host}} (opcional)",
    title: "Importar proyecto y conversaciones",
    description: "Trae un proyecto y sus conversaciones a {{brandName}}",
    daemon: "En {{host}}",
    computer: "Este equipo",
    source: "Origen de las conversaciones",
    destination: "Directorio del proyecto en {{host}}",
    hint: "Usa un directorio existente para combinar conversaciones o uno nuevo para transferir archivos. El código existente nunca se sobrescribe.",
    code: "Elegir archivos del proyecto",
    conversations: "Elegir conversaciones JSONL de Claude o Codex",
    files: "{{count}} archivos seleccionados",
    history:
      "Las conversaciones subidas son solo historial de texto. No pueden reanudar la sesión original. No se importan herramientas ni adjuntos.",
    native: "Las conversaciones del daemon usan la importación nativa del proveedor.",
    preview: "Vista previa",
    import: "Importar selección",
    cancel: "Cancelar",
    close: "Cerrar",
    busy: "Procesando…",
    progress: "Subiendo {{done}} / {{total}} bytes",
    empty: "No se encontraron conversaciones importables en este directorio.",
    resumable: "Sesión del proveedor",
    transcript: "Historial de texto",
    complete: "Importación finalizada",
    imported: "{{count}} conversaciones importadas o ya existentes",
    failures: "Algunas conversaciones no se pudieron importar. Puedes reintentar las restantes.",
    saved: "Conversaciones importadas guardadas",
    more: "Cargar más",
    back: "Atrás",
    localUnavailable:
      "La importación local está disponible en escritorio o web. Aquí puedes importar desde el daemon.",
  },
  fr: {
    exportsDirectory: "Dossier des conversations exportées sur {{host}} (facultatif)",
    title: "Importer un projet et ses conversations",
    description: "Ajouter un projet et ses conversations à {{brandName}}",
    daemon: "Sur {{host}}",
    computer: "Cet ordinateur",
    source: "Source des conversations",
    destination: "Dossier du projet sur {{host}}",
    hint: "Choisissez un dossier existant pour fusionner les conversations ou un nouveau pour transférer les fichiers. Le code existant reste intact.",
    code: "Choisir les fichiers du projet",
    conversations: "Choisir des conversations JSONL Claude ou Codex",
    files: "{{count}} fichiers sélectionnés",
    history:
      "Les conversations transférées sont uniquement du texte. Elles ne reprennent pas la session d’origine. Les outils et pièces jointes ne sont pas importés.",
    native: "Les conversations du daemon utilisent l’importation native du fournisseur.",
    preview: "Aperçu",
    import: "Importer la sélection",
    cancel: "Annuler",
    close: "Fermer",
    busy: "Traitement…",
    progress: "Transfert de {{done}} / {{total}} octets",
    empty: "Aucune conversation importable dans ce dossier.",
    resumable: "Session du fournisseur",
    transcript: "Historique texte",
    complete: "Importation terminée",
    imported: "{{count}} conversations importées ou déjà présentes",
    failures:
      "Certaines conversations n’ont pas été importées. Réessayez pour les éléments restants.",
    saved: "Conversations importées enregistrées",
    more: "Charger la suite",
    back: "Retour",
    localUnavailable:
      "L’importation locale est disponible sur ordinateur ou sur le web. Vous pouvez importer depuis le daemon ici.",
  },
  ja: {
    exportsDirectory: "{{host}}上のエクスポート済み会話フォルダー（任意）",
    title: "プロジェクトと会話をインポート",
    description: "プロジェクトと会話を{{brandName}}に取り込みます",
    daemon: "{{host}}上",
    computer: "このコンピューター",
    source: "会話の場所",
    destination: "{{host}}上のプロジェクトフォルダー",
    hint: "既存フォルダーには会話を統合し、新規フォルダーにはファイルを転送します。既存コードは上書きしません。",
    code: "プロジェクトファイルを選択",
    conversations: "ClaudeまたはCodexのJSONL会話を選択",
    files: "{{count}}個のファイルを選択済み",
    history:
      "アップロードした会話はテキスト履歴のみです。元のセッションは再開できません。ツール呼び出しと添付ファイルは取り込みません。",
    native: "デーモン上の会話はプロバイダーのネイティブインポートを使います。",
    preview: "プレビュー",
    import: "選択項目をインポート",
    cancel: "キャンセル",
    close: "閉じる",
    busy: "処理中…",
    progress: "{{done}} / {{total}}バイトを転送中",
    empty: "このフォルダーに取り込める会話はありません。",
    resumable: "プロバイダーセッション",
    transcript: "テキスト履歴",
    complete: "インポート完了",
    imported: "{{count}}件の会話を取り込み済み、または既存です",
    failures: "一部の会話を取り込めませんでした。残りの項目を再試行できます。",
    saved: "保存されたインポート会話",
    more: "さらに読み込む",
    back: "戻る",
    localUnavailable:
      "ローカルインポートはデスクトップまたはウェブで利用できます。ここではデーモンから取り込めます。",
  },
  ko: {
    exportsDirectory: "{{host}}의 내보낸 대화 폴더 (선택 사항)",
    title: "프로젝트 및 대화 가져오기",
    description: "프로젝트와 대화를 {{brandName}}로 가져옵니다",
    daemon: "{{host}}에서",
    computer: "이 컴퓨터",
    source: "대화 원본",
    destination: "{{host}}의 프로젝트 폴더",
    hint: "기존 폴더에는 대화를 병합하고 새 폴더에는 파일을 전송합니다. 기존 코드는 덮어쓰지 않습니다.",
    code: "프로젝트 파일 선택",
    conversations: "Claude 또는 Codex JSONL 대화 선택",
    files: "파일 {{count}}개 선택됨",
    history:
      "업로드한 대화는 텍스트 기록입니다. 원래 세션을 재개할 수 없습니다. 도구 호출과 첨부 파일은 가져오지 않습니다.",
    native: "데몬의 대화는 공급자의 기본 세션 가져오기를 사용합니다.",
    preview: "미리 보기",
    import: "선택 항목 가져오기",
    cancel: "취소",
    close: "닫기",
    busy: "처리 중…",
    progress: "{{done}} / {{total}}바이트 업로드 중",
    empty: "이 폴더에서 가져올 대화를 찾지 못했습니다.",
    resumable: "공급자 세션",
    transcript: "텍스트 기록",
    complete: "가져오기 완료",
    imported: "대화 {{count}}개를 가져왔거나 이미 존재합니다",
    failures: "일부 대화를 가져오지 못했습니다. 남은 항목을 다시 시도할 수 있습니다.",
    saved: "저장된 가져온 대화",
    more: "더 불러오기",
    back: "뒤로",
    localUnavailable:
      "로컬 가져오기는 데스크톱이나 웹에서 사용할 수 있습니다. 여기서는 데몬에서 가져올 수 있습니다.",
  },
  "zh-CN": {
    exportsDirectory: "{{host}} 上导出的对话目录（可选）",
    title: "导入项目和对话",
    description: "将项目及其对话导入 {{brandName}}",
    daemon: "在 {{host}} 上",
    computer: "此电脑",
    source: "对话来源",
    destination: "{{host}} 上的项目目录",
    hint: "使用现有目录合并对话，或使用新目录传输项目文件。不会覆盖现有代码。",
    code: "选择项目文件",
    conversations: "选择 Claude 或 Codex JSONL 对话",
    files: "已选择 {{count}} 个文件",
    history: "上传的对话仅为文本历史记录，无法恢复原始会话。不导入工具调用和附件。",
    native: "守护进程上的对话使用提供商原生会话导入。",
    preview: "预览导入",
    import: "导入所选内容",
    cancel: "取消",
    close: "关闭",
    busy: "处理中…",
    progress: "正在上传 {{done}} / {{total}} 字节",
    empty: "此目录中未找到可导入的对话。",
    resumable: "提供商会话",
    transcript: "文本历史",
    complete: "导入完成",
    imported: "已导入或已存在 {{count}} 个对话",
    failures: "部分对话无法导入。可以重试剩余项目。",
    saved: "已保存的导入对话",
    more: "加载更多",
    back: "返回",
    localUnavailable: "本地导入适用于桌面版或网页版。此处可以从守护进程导入。",
  },
  ru: {
    exportsDirectory: "Каталог экспортированных разговоров на {{host}} (необязательно)",
    title: "Импорт проекта и разговоров",
    description: "Перенесите проект и его разговоры в {{brandName}}",
    daemon: "На {{host}}",
    computer: "Этот компьютер",
    source: "Источник разговоров",
    destination: "Каталог проекта на {{host}}",
    hint: "Выберите существующий каталог для объединения разговоров или новый для переноса файлов. Существующий код не перезаписывается.",
    code: "Выбрать файлы проекта",
    conversations: "Выбрать разговоры Claude или Codex в JSONL",
    files: "Выбрано файлов: {{count}}",
    history:
      "Загруженные разговоры — только текстовая история. Исходный сеанс нельзя продолжить. Вызовы инструментов и вложения не импортируются.",
    native: "Разговоры на демоне используют собственный импорт сеансов провайдера.",
    preview: "Предпросмотр",
    import: "Импортировать выбранное",
    cancel: "Отмена",
    close: "Закрыть",
    busy: "Обработка…",
    progress: "Загрузка {{done}} / {{total}} байт",
    empty: "В этом каталоге нет разговоров для импорта.",
    resumable: "Сеанс провайдера",
    transcript: "Текстовая история",
    complete: "Импорт завершён",
    imported: "Импортировано или уже существует разговоров: {{count}}",
    failures: "Некоторые разговоры не удалось импортировать. Можно повторить оставшиеся.",
    saved: "Сохранённые импортированные разговоры",
    more: "Загрузить ещё",
    back: "Назад",
    localUnavailable:
      "Локальный импорт доступен в настольном или веб-приложении. Здесь можно импортировать с демона.",
  },
  "pt-BR": {
    exportsDirectory: "Diretório de conversas exportadas em {{host}} (opcional)",
    title: "Importar projeto e conversas",
    description: "Traga um projeto e suas conversas para o {{brandName}}",
    daemon: "Em {{host}}",
    computer: "Este computador",
    source: "Origem das conversas",
    destination: "Diretório do projeto em {{host}}",
    hint: "Use um diretório existente para mesclar conversas ou um novo para transferir arquivos. O código existente nunca é sobrescrito.",
    code: "Escolher arquivos do projeto",
    conversations: "Escolher conversas JSONL do Claude ou Codex",
    files: "{{count}} arquivos selecionados",
    history:
      "As conversas enviadas são apenas histórico de texto. Não retomam a sessão original. Chamadas de ferramentas e anexos não são importados.",
    native: "As conversas do daemon usam a importação nativa do provedor.",
    preview: "Prévia da importação",
    import: "Importar seleção",
    cancel: "Cancelar",
    close: "Fechar",
    busy: "Processando…",
    progress: "Enviando {{done}} / {{total}} bytes",
    empty: "Nenhuma conversa importável encontrada neste diretório.",
    resumable: "Sessão do provedor",
    transcript: "Histórico de texto",
    complete: "Importação concluída",
    imported: "{{count}} conversas importadas ou já existentes",
    failures: "Algumas conversas não foram importadas. Você pode tentar novamente as restantes.",
    saved: "Conversas importadas salvas",
    more: "Carregar mais",
    back: "Voltar",
    localUnavailable:
      "A importação local está disponível no desktop ou na web. Aqui você pode importar do daemon.",
  },
  ar: {
    exportsDirectory: "مجلد المحادثات المصدّرة على {{host}} (اختياري)",
    title: "استيراد مشروع ومحادثات",
    description: "أضف مشروعًا ومحادثاته إلى {{brandName}}",
    daemon: "على {{host}}",
    computer: "هذا الكمبيوتر",
    source: "مصدر المحادثات",
    destination: "مجلد المشروع على {{host}}",
    hint: "استخدم مجلدًا موجودًا لدمج المحادثات أو مجلدًا جديدًا لنقل الملفات. لن يُستبدل الكود الموجود.",
    code: "اختيار ملفات المشروع",
    conversations: "اختيار محادثات Claude أو Codex بصيغة JSONL",
    files: "تم اختيار {{count}} ملفات",
    history:
      "المحادثات المرفوعة سجل نصي فقط. لا يمكن استئناف الجلسة الأصلية. لا تُستورد استدعاءات الأدوات والمرفقات.",
    native: "تستخدم محادثات الخادم استيراد الجلسات الأصلي للمزوّد.",
    preview: "معاينة الاستيراد",
    import: "استيراد المحدد",
    cancel: "إلغاء",
    close: "إغلاق",
    busy: "جارٍ العمل…",
    progress: "رفع {{done}} / {{total}} بايت",
    empty: "لم يتم العثور على محادثات قابلة للاستيراد في هذا المجلد.",
    resumable: "جلسة المزوّد",
    transcript: "سجل نصي",
    complete: "اكتمل الاستيراد",
    imported: "تم استيراد {{count}} محادثات أو أنها موجودة بالفعل",
    failures: "تعذّر استيراد بعض المحادثات. يمكنك إعادة محاولة العناصر المتبقية.",
    saved: "المحادثات المستوردة المحفوظة",
    more: "تحميل المزيد",
    back: "رجوع",
    localUnavailable:
      "الاستيراد المحلي متاح في تطبيق الكمبيوتر أو الويب. يمكنك الاستيراد من الخادم هنا.",
  },
};
