// @ts-check
import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";

const repo = "https://github.com/frogg-app/frogg";

/** Top-level docs directories, in sidebar order. Each is autogenerated from its pages' `sidebar.order`. */
const sections = [
  ["getting-started", "Getting started"],
  ["using-frogg", "Using Frogg"],
  ["agents-and-providers", "Agents & providers"],
  ["desktop-mobile-cli", "Desktop, mobile & CLI"],
  ["self-hosting", "Self-hosting the daemon"],
  ["fork-and-rebrand", "Fork & rebrand"],
  ["contributing", "Contributing"],
  ["reference", "Reference"],
];

export default defineConfig({
  site: "https://frogg.app",
  // Workspaces were renamed to sessions; shipped clients still link to the old page.
  redirects: {
    "/docs/using-frogg/projects-and-workspaces": "/docs/using-frogg/projects-and-sessions",
  },
  trailingSlash: "ignore",
  prefetch: { prefetchAll: true, defaultStrategy: "hover" },
  build: { inlineStylesheets: "always" },
  integrations: [
    starlight({
      title: "Frogg",
      description:
        "Frogg runs and monitors coding agents on a daemon you host, from desktop, phone, browser and CLI.",
      logo: { src: "./src/assets/brand/frogg-logo.png", alt: "Frogg" },
      favicon: "/favicon.png",
      social: [{ icon: "github", label: "GitHub", href: repo }],
      editLink: { baseUrl: `${repo}/edit/main/website/` },
      lastUpdated: false,
      customCss: ["./src/styles/tokens.css", "./src/styles/starlight.css"],
      // The landing page provides its own 404 so both halves of the site share one.
      disable404Route: true,
      components: {
        ThemeProvider: "./src/components/starlight/ThemeProvider.astro",
        ThemeSelect: "./src/components/starlight/ThemeSelect.astro",
        SiteTitle: "./src/components/starlight/SiteTitle.astro",
      },
      head: [
        { tag: "link", attrs: { rel: "apple-touch-icon", href: "/apple-touch-icon.png" } },
        { tag: "meta", attrs: { name: "theme-color", content: "#0f1312" } },
        { tag: "meta", attrs: { property: "og:image", content: "https://frogg.app/og.png" } },
      ],
      sidebar: sections.map(([dir, label]) => ({
        label,
        collapsed: dir === "reference" || dir === "contributing",
        items: [{ autogenerate: { directory: `docs/${dir}` } }],
      })),
    }),
  ],
});
